### ISSUE TITLE
Manage Pledge: Revise copy in manage email

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#102]
Once you fill in your email to generate the link to the pledge management form, it sends you an email with that link. Currently the email is very terse:

```
Subject: Updating your Pledge

Howdy, please open this link to update your pledge:

[URL]
```

It would be nice to maybe thank the org again, or at least make a reference to Five for the Future aside from just in the URL.

**Comment by angelasjin** [comment]
How about something along the lines of:

Subject: Next steps to update your Pledge

Hi there! 

Thanks for submitting your email! Here is the link to update your pledge:

[URL]

If you have any questions about how to update your pledge, or about Five for the Future in general, please visit [URL].

Thanks for participating in Five for the Future. Your contribution ensures that WordPress continues to thrive! 

Sincerely,
