### ISSUE TITLE
Manage Pledge: Allow pledge admins to change email

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#107]
#105 kicks off getting the manage form to work, but skips the email field. If the email changes, we need to re-verify that the email is valid.

Once the form is submitted and the email is now unconfirmed, should we switch the whole pledge back into "pending" status? If so, we'll want to communicate that to the person editing it, both before they change it and once the pledge is saved (since they suddenly won't be able to see it).

Or should we not allow the email to be changed on this form, only by contacting us?

cc @andreamiddleton, @coreymckrill

**Comment by andreamiddleton** [comment]
I think we should let people change the email themselves, and then add an admin note that until the email is confirmed, the pledge will be held in Pending status and won't be visible.
