### ISSUE TITLE
Create a pledge: create contributors posts

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#11]
When a new pledge is created (or an existing pledge updated), we should create Contributor posts for each listed contributor. This may need a new CPT?

- Each Contributor post will have the pledge as a parent. 
- Each contributor post is associated with one pledge. Thus, there can be multiple posts for the same contributor if they are linked to multiple pledges.
- Contributor posts should include meta data about when the contributor confirmed their connection to the pledge

**Comment by coreymckrill** [comment]
Updated the description to add item about meta data for the confirmation date. Based on [this screenshot](https://github.com/WordPress/five-for-the-future/issues/30#issuecomment-540792238).

**Comment by coreymckrill** [comment]
Actually, maybe we don't need a post meta field for the confirmation date. Confirming will cause the contributor post to get set to `publish`, so the publish date in the `wp_posts` table should reflect the date of confirmation.

**Comment by coreymckrill** [comment]
Noting that this enables work on #12
