### ISSUE TITLE
Create Pledge: Check for spam submissions

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#118]
Use akismet to check if a new pledge is spam. Can add the check in `check_invalid_submission`. The spam check would only be on the description field. All this is technically fine :) But there are a few workflow questions:

If a new submission is spam, what kind of feedback should we give the pledge creator, if any? We could refuse to create the pledge & error message at them; or silently discard the pledge with no feedback; or create the pledge with a new "spam" status?

What if it's incorrectly flagged as spam? What recourse would there be for someone who creates a ham-pledge?

What if someone updates a pledge and adds spam, should it flip to deactivated?

cc @coreymckrill @iandunn @andreamiddleton

**Comment by ryelle** [comment]
Another question is "is this happening enough to prioritize fixing it", i suppose.

**Comment by iandunn** [comment]
I'd personally "wait and see" how bad the spam gets; so far we've only had 3 entries.  When #36 is done, teams will instantly be notified when (infrequent) spamming occurs, so it'd get taken down quickly.

If it becomes a time-consuming task, though, then I agree that it'd be worth automating.

**Comment by andreamiddleton** [comment]
@ryelle I think your question of "is it happening enough to prioritize fixing" is spot-on. This is a non-essential program -- ie, if a pledge goes to spam, it doesn't actually stop anyone from doing the work, just from getting credit in this one place -- so I think we can wait and see if this becomes a big enough problem.

**Comment by ryelle** [comment]
>  if a pledge goes to spam, it doesn't actually stop anyone from doing the work

Just clarifying that right now, we do not spam pledges– the issue is that spammy pledges are being shown on the site until someone catches it.

My question is "are we seeing enough spam to merit adding in a spam-check", which I still think is no- we also have the "deactivate" status now, so it's easy for a site admin to go in and remove the pledge. If we see an uptick in spam we can bring this back up.

**Comment by pkevan** [comment]
No movement on this in a while, so closing.
