### ISSUE TITLE
Pledge List: Only show pledges with confirmed contributors

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#13]
Pledges can be published without contributors, but they shouldn't appear in the list until they have at least one published child-post Contributor.

**Comment by coreymckrill** [comment]
Related: #52

**Comment by iandunn** [comment]
Is this working in your environment? In mine I see published pledges with 0 confirmed contributors showing up in the archive template.

**Comment by ryelle** [comment]
Yes, it was working but we commented it out to test on production since we couldn't confirm people there - see the comment I just left https://github.com/WordPress/five-for-the-future/pull/43#issuecomment-547536892

**Comment by iandunn** [comment]
Ah, perfect, thanks! Done in 6209060
