### ISSUE TITLE
Publicize Team Pledges page

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#130]
Continuation of #69 

Now that it exists, how do we let people know?

See https://github.com/WordPress/five-for-the-future/issues/69#issuecomment-562729711 for background.

**Comment by ryelle** [comment]
Copying over the relevant comment from @iandunn 

> The two things that jump to mind are:
>
> 1. Publishing a post on make/Updates
> 2. Automatically add a widget to the bottom of each team's sidebar. It could show avatars like https://wordpress.org/five-for-the-future/pledges/, or just be a text link to the page.
>
> I like the idea of doing both, because if we only write the make/Updates post, then most people won't be aware, because they don't read that site, and even those who do will eventually forget how to find the info and have to dig through old posts to find the link.
>
> If we only do the sidebar widget, then most people will never notice that it's there.
>
> If we do both, though, then I think the combination will create enough institutional knowledge to make it something that most active contributors are aware of.

**Comment by ryelle** [comment]
I think both makes sense — make/updates will notify everyone now, and links in the p2's sidebar will keep it "in view" for everyone (who pays attention to that 🙂).

Personally, I don't think we should do avatars, but that's not a strongly-held opinion. If we do use avatars, it should probably only be a random subset of maybe… 3 or 4 rows, however many fit.

I think we should also add a blurb above each pledge, describing what the list is– but each team rep could maybe write that, since it's just post content above the shortcode (it _is_ a shortcode, right?)

**Comment by iandunn** [comment]
Adding `blocked` since I don't think it makes sense to publicize this before #129 is done.

**Comment by iandunn** [comment]
> Personally, I don't think we should do avatars, but that's not a strongly-held opinion. If we do use avatars, it should probably only be a random subset of maybe… 3 or 4 rows, however many fit.

That's a good point, there's probably way to many for it to be useful. Given that, I'd probably lean towards just not including them at all.

**Comment by iandunn** [comment]
> I think we should also add a blurb above each pledge, describing what the list is– but each team rep could maybe write that, since it's just post content above the shortcode (it is a shortcode, right?)

Are you talking about the sidebar widget, or the Team Pledges page? The latter isn't a shortcode (see `mu-plugins/make-network/team-pledges.php`), but it might be better to discuss changes to that page in a new issue, unless I'm missing how that's relevant to this one?

If you're talking about the widget, were you envisioning it having a list of all pledges/companies whose sponsored contributors selected the current team? I was thinking that it'd just be a "Team Pledges" link and nothing else. The page being linked to also includes volunteer contributors, so I don't think we should highlight sponsored contributors more than volunteer in this context.

**Comment by ryelle** [comment]
> Are you talking about the sidebar widget, or the Team Pledges page? The latter isn't a shortcode (see mu-plugins/make-network/team-pledges.php), but it might be better to discuss changes to that page in a new issue, unless I'm missing how that's relevant to this one?

It's not directly relevant, just an idea I had and wanted to see if it had merit. I meant the team pledges page, right now it's just a list of people with very little context. Some content like "how to get listed here" or "why am I listed here", with a link off to the Five for the Future site would be helpful.

**Comment by iandunn** [comment]
> It's not directly relevant, just an idea I had and wanted to see if it had merit. 

👍 I opened #135  to discuss that

**Comment by iandunn** [comment]
Added the sidebar link in `dotorg 15662`:

Example: https://make.wordpress.org/meta/ (at the bottom)

> Team Pledges
>
> 135 people have committed to contribute to the Meta team every week. When you need help with a task or project, reach out to these people!

Is everyone happy with that copy, or should we make some tweaks?

**Comment by ryelle** [comment]
Works for me– since you've already committed that, can you close this issue? or does something else need to happen?

**Comment by iandunn** [comment]
I was thinking of r15662 as a first version, and wanted to wait to see if anyone wanted any iterations before closing this out.

If nobody does, though, I'm happy to.

**Comment by andreamiddleton** [comment]
I think I prefer:

> (2,000) people have pledged time to contribute to (Community) Team efforts! When looking for help on a project or program, try starting by reaching out to the people on this list!

What do you think, too gentle? :)

**Comment by iandunn** [comment]
That WFM :)

Done in `dotorg 15684` and https://meta.trac.wordpress.org/changeset/9383/

I made minor tweaks for context:

### Sidebar Variant

> 468 people have pledged time to contribute to Community Team efforts! When looking for help on a project or program, try starting by reaching out to them! 

Replaced `people on this list` with `them`, since the list is only linked to in this context.

### Page Intro Variant:

> These people have pledged time to contribute to Community Team efforts! When looking for help on a project or program, try starting by reaching out to the people on this list! 

Replaced `2000 people` with `These people` since the people being referred to are directly below the copy in this context.

### Iteration

I'm gonna close this on the assumption that those are ok, but I'm happy to make further tweaks. Please reopen this if anyone would like any.
