### ISSUE TITLE
Team Pledges page: contributor sorting should be case-insensitive

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/five-for-the-future#136]
Looking at the Make/Meta page for pledged contributors:

https://make.wordpress.org/meta/pledges/

The contributors appear to be sorted alphabetically, but if you scroll down to the bottom, you'll see that all display names that begin with a lowercase letter are listed below those starting with an uppercase letter. I'm guessing this is because the sort function is actually using the ASCII value.

One possible solution might be to do some ASCII transliteration before sorting, like in [this function](https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/mu-plugins/3-helpers-misc.php#L97-L113). Or, more simply, use a custom sort function that sets everything to lowercase before assessing the sort order (without actually changing what gets displayed).

**Comment by iandunn** [comment]
Good catch, fixed in `dotorg 15665`. You can see the new results for Meta; the other teams will need about 24 hours for the object cache to be refreshed.
