### ISSUE TITLE
Team Pledges widget is extra large on handbook pages

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#137]
Since the widget is dynamically added to each sidebar, this is also added to the handbook pages, where the styles are causing it to display using extra-large text:

![Screen Shot 2019-12-18 at 10 03 15 AM](https://user-images.githubusercontent.com/541093/71097217-a751b580-217d-11ea-80c3-5503f10c14a5.png)

This should probably be removed from the handbook pages, it's only useful in the context of the team p2s.

_[This was reported on slack here.](https://wordpress.slack.com/archives/C02QB8GMM/p1576666711163000)_

**Comment by ryelle** [comment]
Fixed in dotorg#15668 — I restricted the widget to only show on `sidebar-1`, which is the p2 sidebar.

**Comment by iandunn** [comment]
Good catch 👍
