### ISSUE TITLE
Wrong teams count in contributor's summary message

### ISSUE THREAD

**Issue by SergeyBiryukov** [WordPress/five-for-the-future#139]
1. Looking at https://make.wordpress.org/support/pledges/, `...and 2 other teams` is displayed for everyone contributing to more than 3 teams, which is not accurate for 4, 5 teams, etc.

This is caused by defaulting to `...and 2 other teams` in `get_contributor_summary_message()` for counts other than 1 or 2. The correct number should be displayed instead.

Reported by @fierevere.

2. On a related note, the comment in `wporg-breathe/content-pledge.php` has a wrong function name:
```
/*
 * Note: There will be a large number of contributors on every page, so don't call any expensive functions like
 * `get_avatar_url( $user_id )` here (which creates a database lookup for the email address). Instead, add the
 * data to `get_contributors()` in a performant way.
 */
```
After spending some time trying to find the `get_contributors()` function, it turned out it's called `get_team_contributors()`.

**Comment by iandunn** [comment]
Thanks for spotting that! 

Fixed in `dotorg 15685` and https://meta.trac.wordpress.org/changeset/9385/.

I updated `/support/` and a few others manually, but the rest will automatically update in `< 24 hours` when the object cache expires.
