### ISSUE TITLE
Pledge List: Shortcode? Block? Archive?

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#14]
[Figma link for the list mockup](https://www.figma.com/file/OirvZ8jLK3CNzVHnmAYjbufc/Five-for-the-Future?node-id=254%3A955)

Currently in the plugin, this is a shortcode (with notes about making it a block). It can be very self-contained, we can easily add different pagination, the potential for infinite scroll, etc. We have total control, but need to do more work.

The new design was intended to be an archive page– it has pagination, a search box, and a "sort by" filter. Pagination is default, we could probably stick with WordPress search (even though it would not be restricted to pledges, there's hardly any other content) or do something custom. We can do the filtering by hooking into `pre_get_posts`. If we wanted to add a JS enhancement later, we could do it on top of the archive template.

So– thoughts? How should we move forward here❓

**Comment by coreymckrill** [comment]
Using the archive is simplest, whether we do it primarily with PHP templates or JS. That would be my vote.

If we had a use case or a design that called for displaying a list of pledges in the sidebar of another page, or other arbitrary places on the site, it would probably make sense to put in the extra effort to make it a shortcode/block. But I don't think we have that use case right now.

**Comment by iandunn** [comment]
wfm

**Comment by ryelle** [comment]
Closing this discussion-issue in favor of the actionable #32 🙂
