### ISSUE TITLE
Pledges template omits canonical URL tags

### ISSUE THREAD

**Issue by jonoalderson** [WordPress/five-for-the-future#142]
The "Pledges" template at https://wordpress.org/five-for-the-future/pledges/ lacks a canonical URL tag.

A canonical URL tag should be implemented, with the following conditions:
- Sort/filter parameters should be ignored
- Pagination components should be included when present.
- Search results should be omitted

E.g:
https://wordpress.org/five-for-the-future/pledges/page/2/?order=alphabetical becomes https://wordpress.org/five-for-the-future/pledges/page/2/

https://wordpress.org/five-for-the-future/pledges/?order=alphabetical becomes https://wordpress.org/five-for-the-future/pledges/

https://wordpress.org/five-for-the-future/?s=yoast should omit the tag

**Comment by iandunn** [comment]
Looks like this is a duplicate of #80
