### ISSUE TITLE
Pledge Organization page: Badge Icon and style missing for 'Themes Team' 

### ISSUE THREAD

**Issue by rupok** [WordPress/five-for-the-future#146]
Currently "Thems Team" badge shows like this on any pledge organization page :

![pledge-organization](https://user-images.githubusercontent.com/3213988/84354530-dacc4480-abe2-11ea-8575-e3cf6f71766b.png)

I see themes team is missing from the `switch statement` in theme's `functions.php` as well as no style defined in `_team_badges.scss`

**Comment by Asif2BD** [comment]
I also see it for any page with 'Themes Team' badge, example -
https://wordpress.org/five-for-the-future/pledge/automattic/
https://wordpress.org/five-for-the-future/pledge/wpmu-dev/
https://wordpress.org/five-for-the-future/pledge/wpdeveloper/

**Comment by ryelle** [comment]
@iandunn I _think_ this might be related to the Theme Review Team -> Themes Team rename (from https://github.com/WordPress/five-for-the-future/issues/83)? Should there be two different theme-related teams?

**Comment by rupok** [comment]
I see a meta ticket about this too - https://meta.trac.wordpress.org/ticket/4943

I am confused too about the difference between **Themes Team** and **Theme Review Team**

**Comment by iandunn** [comment]
🤔 It's been awhile, but at first glance it does look like at "Themes Team" one should be "Theme Review Team". So maybe some instance of it were missed, or maybe there's some way that people can still submit the old name.

**Comment by pattonwebz** [comment]
The team was renamed - but not a new team created. It was renamed to better reflect what the team has been doing. 'Review' has been just one part of the process for several years.

If there are problems with the rename needing references adapted in other places I was unaware of the places it would need changes. I assumed it was propagated from the name of the team and not hardcoded anywhere so I did not think to search around for references about where or how it is managed in all the locations it may be used :(

**Comment by iandunn** [comment]
You don't need to, the 5ftF site needs some special handling to avoid people misunderstanding the context, and entering inaccurate data. See #83 for details.

**Comment by pattonwebz** [comment]
@iandunn I realise I was not clear so just to clarify:

The team used to be called `Theme Review Team`. Recently (after 5ftF launched - I don't remember when exactly) the _name_ of the team was adjusted to `Themes Team` via the buddypress interface for badges.

I think that has caused a ripple effect and perhaps more needs done to allow a name change to happen than actually just adjusting the name via the interface.

**Comment by iandunn** [comment]
Ah, I see, that's a really helpful clue.

**Comment by coreymckrill** [comment]
This should be fixed now, via r17406 in dotorg svn.

**Comment by pattonwebz** [comment]
Confirmed the badge shows.
