### ISSUE TITLE
Create a pledge: Form submission validation

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#15]
- Check that pledge owner email is unique
- Check that website address is unique
- Check that there is at least one contributor

Success and error messages should be descriptive. The design has the following on success:

![Screen Shot 2019-10-02 at 2 35 40 PM](https://user-images.githubusercontent.com/541093/66071925-065e4180-e522-11e9-8467-75eed17a242e.png)

**Comment by coreymckrill** [comment]
> Check that website address is unique

Clarification here: I think we should check if the _domain_ is unique. A URL can have infinite variations while still having the same domain.
