### ISSUE TITLE
Missing singular form for "1 hour per week"

### ISSUE THREAD

**Issue by SergeyBiryukov** [WordPress/five-for-the-future#152]
Apparently if you specify 1 hour of contributions per week, it shows up as "1 hours", as currently seen on https://profiles.wordpress.org/ireneyoast/:
> Irene Strikkers contributes 1 hours per week to the following teams: Core, Marketing.

That should be "1 hour per week".

**Comment by iandunn** [comment]
Thanks! Fixed in `r18665-dotorg`
