### ISSUE TITLE
 Theme: The child theme's `navigation.js` file is not used

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#156]
The child theme contains a `navigation.js` file, but then enqueues the navigation.js from the parent theme.

https://github.com/WordPress/five-for-the-future/blob/325a6d71e2d08533dc923af42fdfe1de17cd8468/themes/wporg-5ftf/functions.php#L128

See related issue in Learn: https://github.com/WordPress/learn/issues/204; and meta trac ticket to update the parent theme to correctly register this script: [#5687-meta](https://meta.trac.wordpress.org/ticket/5687) - then the child theme could just use `wp_enqueue_script( 'wporg-navigation' )`.

**Comment by iandunn** [comment]
Removed in 77faa74b059e2966e80bdd167b7aa0cc370fcb1c
