### ISSUE TITLE
Five for the future - post thumbnails on Pledges page do not load

### ISSUE THREAD

**Issue by mbootsman** [WordPress/five-for-the-future#161]
Post thumbnails on this page do not load: https://wordpress.org/five-for-the-future/pledges/?order=contributors
When requesting the image itself an empty canvas is shown.
![2021-06-23_14-13](https://user-images.githubusercontent.com/5878082/123094799-9dbda380-d42d-11eb-9a02-38d994db50ef.png)

**Comment by coreymckrill** [comment]
There was a temporary issue with some images loading across all the dotorg sites. More discussion [here](https://wordpress.slack.com/archives/C02QB8GMM/p1624464360066400).

It appears that the logos are loading again now.
