### ISSUE TITLE
Remove build files from git repo

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#17]
Since the built CSS files are tracked, we're going to run into merge conflicts in most PRs, and they're annoying to resolve.

Is there a reason we need to track the built files in git, or can we leave that for just the SVN sync?

**Comment by coreymckrill** [comment]
I'd vote for removing them.

**Comment by ryelle** [comment]
Do we need the [style-rtl.css](https://github.com/WordPress/five-for-the-future/blob/production/themes/wporg-5ftf/css/style-rtl.css) file? If so, we should generate it with `grunt-rtlcss`, but the site itself is in English so I don't think we need RTL styles. If it seems like this will be translated, maybe we can add it then?

**Comment by iandunn** [comment]
wfm
