### ISSUE TITLE
5FTF: Photos Team icon not displaying on company pledge page

### ISSUE THREAD

**Issue by dream-encode** [WordPress/five-for-the-future#171]
Example: https://wordpress.org/five-for-the-future/pledge/3ymedia-comunicacion-digital/

![image](https://user-images.githubusercontent.com/1900750/159812626-5034d467-387d-4641-a47d-a892dbf8fed4.png)

**Comment by iandunn** [comment]
[There isn't a badge for the Photos team yet](https://meta.trac.wordpress.org/ticket/5981), so for now I just used the `camera` dashicon that @lukecarbis [suggested](https://meta.trac.wordpress.org/ticket/5988).

We can update that whenever the final badge icon/colors are decided.

cc @coffee2code
