### ISSUE TITLE
Manual "props" for team activity

### ISSUE THREAD

**Issue by tellyworth** [WordPress/five-for-the-future#174]
Proposal for discussion:

Team reps and other key team members should have a mechanism for giving props or otherwise manually crediting people for making contributions for the team that aren't otherwise captured in profile activity.

The idea of recording #props channel activity in profiles was already mentioned in #169, that would be one way that's worth pursuing.

Are there other methods needed by some teams, besides literal "props"?

**Comment by courtneyr-dev** [comment]
Activity as a WP user on team sites + LearnWP, HelpHub, DevHub, WPTV come to mind. Can we track user activity on-site and then review for manual props?

**Comment by StevenDufresne** [comment]
> Can we track user activity on-site and then review for manual props?

What would be considered "activity on-site"? Can you give an example?

**Comment by tellyworth** [comment]
I think we can close this as done now that the #props channel is recorded in profiles. Team reps can monitor contributions using whatever method they choose, and use the #props channel to manually thank people.

**Comment by iandunn** [comment]
👍🏻
