### ISSUE TITLE
There is no space between search and filter in mobile size, due to which the design is deteriorating.

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/five-for-the-future#175]
When you open [https://wordpress.org/five-for-the-future/pledges/](https://wordpress.org/five-for-the-future/pledges/) site on a screen below 572 pixels, there is no space between search and filter in mobile size, because of this the design does not look good.

Site Link => [https://wordpress.org/five-for-the-future/pledges/](https://wordpress.org/five-for-the-future/pledges/)

I have added a screenshot of the issue below.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/72435501/161240070-d421e18c-ed22-4645-8966-6f84845fee6c.png">

**Comment by iandunn** [comment]
Good catch, thanks!
