### ISSUE TITLE
Confirmed vs Sponsored Contributor stat is misleading/confusing

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#198]
`5ftf_total_pledged_contributors` is the # of `5ftf_contributor` posts on w.org/5.  `5ftf_total_sponsored_contributors` is all folks who have entered hours on their w.org profile and checked the "sponsored" box.

It's easy to confuse that, and think that `5ftf_total_pledged_contributors` is all contributors who have entered hours on their w.org profile (regardless of whether they're sponsored or volunteer); and that  `5ftf_total_sponsored_contributors` is the # of `5ftf_contributor` posts on w.org/5.

There are two ways to determine if someone is sponsored: if they've checked the box on their profile, or if they have a contributor post on w.org/5. The latter is probably much more reliable since it doesn't require the contributor to manually select it.

* Should we keep both stats, or maybe delete one? Should be add the # of folks who have hours on their w.org profile (regardless of sponsored or not) and count that as the total contributors?
* should we combine the two stats and then de-duplicate the list, and count someone as sponsored if they check the box or have a w.org/5 post?
* We might want to consider renaming those stats to better reflect what they are. It could just be on the front end (once #38  is done), but it'd be better to do it in the code and apply it retroactively to the db, to avoid further confusion. 
* We might also want to consider automatically updating the "sponsored" field based on the w.org/5 posts; or removing it and relying on w.org/5 posts entirely. There may have been a reason we set it up this way, though, so it requires some thought and research.

**Comment by angelasjin** [comment]
That is confusing! @iandunn, where do these numbers and labels show up? It would be helpful to know where this confusion happens. 

As a base, I would like to know: 

1. Total number of contributors
2. Total number of sponsored contributors
3. Total number of pledged and non-sponsored contributors (guessing that's how `5ftf_total_pledged_contributors` came about, because 'non-sponsored' sounds odd. Maybe we could rename to "independent contributors" or something like that?)

I thought that, to tell if someone is sponsored, the company also has to add them. I'd be fine with that as our main way to gather that information. But I agree, having deeper context around why it was set up this way would be helpful.

**Comment by iandunn** [comment]
They come from the unfinished stats page (#38), which is just a private page right now (`https://wordpress.org/five-for-the-future/?page_id=684&preview=true`). The confusion is probably something we'll want to fix before finishing the page and making it public.

The company has to add a contributor in order to create a `pending` contributor post on w.org/5, and then the contributor has to confirm it in order for that post to be published. From the front end, that is what makes their avatar show up for a given company. 

I agree that that's probably a better way to tell if someone is sponsored than if they select the "sponsored" box when editing their w.org profile. It's possible to select that even if someone isn't connected to a 5ftF company, and many who _are_ connected to a company don't select that box for whatever reason. 

Maybe we should automatically synchronize those values when w.org/5 contributor posts are published/unpublished, so folks don't have to manually do it. We may not even need the `sponsored` box on the profile, since we can pull the info directly from w.org/5 instead.

**Comment by christinaworkman** [comment]
I don't have any answers to your questions but rather a potential complication to share. From what I understand, there is a desire to know how many bodies and hours are sponsored vs not. For a couple of years, I was sponsored for roughly 8 hours a month, or 2 hours a week. But I often spent several more hours of my own time contributing. So while I may have contributed for 4 hours a week, only half of that was sponsored. To count all my time towards a sponsored number wouldn't be accurate. But there is no way for me to separate my time. It's either all counted as sponsored, so my employer gets "credit", or I under-report my time. (I wouldn't feel right not claiming sponsorship at all)

**Comment by iandunn** [comment]
Yeah, that's a good point to add. #72 would probably solve that, if we added an option to select "volunteered" in addition to companies.

**Comment by angelasjin** [comment]
I heard the term "self-sponsored contributor" and I like that quite a bit. @iandunn what do you think about using "self-sponsored" vs. "company-sponsored" to help further with further clarification?

**Comment by iandunn** [comment]
That works for me 👍🏻 #124 and #201 have some related discussion where that could be used as well.
