### ISSUE TITLE
Finish Home page template

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#2]
Large screen:

![Home-d](https://user-images.githubusercontent.com/541093/66065303-16bbef80-e515-11e9-9db8-d47eedfdec49.jpg)

Small screen:

![Mobile](https://user-images.githubusercontent.com/541093/66065410-4e2a9c00-e515-11e9-85b7-5f710b274eaf.png)

**Comment by iandunn** [comment]
9c700e59cbbf287acd5c786ebe07d72818acf33b and 78822c4 made some more progress on this.

There's more left to do, but I think it's good enough for now, and we can circle back to it after milestones 1 and 2 are done.

**Comment by ryelle** [comment]
I'm pretty sure this is done now, but needs to be deployed to wp.org so that @melchoyce can check on it.
