### ISSUE TITLE
Create a pledge: Add an input for uploading a logo image

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/five-for-the-future#20]
The pledge listing includes a logo of the organization. During pledge creation, the creator should be able to click a button to choose an image file from their computer to upload as the logo. This image file should be validated when it is uploaded, and added as the featured image on the pledge post.

Some initial thoughts and questions on image requirements:

* 5MB file size limit (this is arbitrary, but seems sufficient for a hi res logo)
* Formats: jpg and png
* Should the logo be cropped to a standardized aspect ratio? If so, the input probably needs explainer text with a request for specific dimensions

**Comment by ryelle** [comment]
Added in #45
