### ISSUE TITLE
Experimental stats before publishing

### ISSUE THREAD

**Issue by tellyworth** [WordPress/five-for-the-future#200]
We need to produce some draft stats for analysis before making any numbers public. That's so we can check things for accuracy, and decide exactly what stats are useful before publishing figures and building reports.

The `[5ftf_stats]` shortcode already dumps some raw numbers. We could start with that, and:

* Use `bump_stats_extra()` or similar to feed it into mc, perhaps as a daily snapshot.
* Build some rough tables or charts on the site, protected by a proxy / user cap check to keep it private (including API endpoints if necessary)

Once we have a first round of charts showing whatever data we have currently, I expect we'd want to refine it by improving the data, adding new charts, etc.

**Comment by tellyworth** [comment]
Updating this: let's keep it in mc initially, using `bump_stats_extra`.

**Comment by iandunn** [comment]
pushing the stats to MC seems easy enough:

1. change the `5ftf__record_snapshot` cron to daily
1. call `bump_stats_extra()` instead of `add_post_meta()` during the cron job

in #38 we can then pull the data from MC instead of the post type
