### ISSUE TITLE
Add `days` button to MC stats

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#213]
Currently the MC `wporg-stats.php` UI only shows 1 year of data by default, and you have to modify the `days` URL param to change that. Adding a input field and button would make that more convenient.

Currently blocked by `https://make.wordpress.org/systems/?p=2109`.

**Comment by dd32** [comment]
I've added a display of how many days is included, and an option to change it.

It's complicated by the fact that the hourly/daily/weekly views had a different number of days included, but with some slightly out-of-the-box thinking, I think I've made it work in a way that's acceptable.
