### ISSUE TITLE
Add "Core Performance Team"  to Contributor Teams list for Profiles

### ISSUE THREAD

**Issue by mxbclang** [WordPress/five-for-the-future#218]
@dd32 asked me to file this request here after [asking about this in Slack](https://wordpress.slack.com/archives/C02QB8GMM/p1667390291007019).

[Core Performance](https://make.wordpress.org/performance/) is the newest core team, added in July 2022. I noticed when editing my wordpress.org profile recently that it is not listed in the Contributor Teams list on the Contribution tab of the edit profile screen:

<img width="984" alt="image" src="https://user-images.githubusercontent.com/12189958/200845468-2fbb0559-d514-4ed7-8c40-06f46209e71f.png">

Can the Core Performance Team be added to this list? Thank you!

**Comment by jeffpaul** [comment]
Wouldn't this be like other Core sub-teams wherein they're covered by the Core team/badge on profiles?

**Comment by mxbclang** [comment]
@jeffpaul I'm not familiar with how that works, so you tell me! If that's how Core teams are usually managed, then I'm fine with that.

**Comment by jeffpaul** [comment]
Open to alternate views/understandings, but that's what I would expect (meaning that the Performance team would fall underneath the Core team).

**Comment by mxbclang** [comment]
@jeffpaul Got it, thank you. Closing this issue.
