### ISSUE TITLE
Sanity check: skip sending emails for blocked accounts

### ISSUE THREAD

**Issue by tellyworth** [WordPress/five-for-the-future#221]
As a short-term fix while we're deciding how to handle #212, let's add some defensive code to the email cron job to skip sending to accounts that are blocked or have some other inactive status.

There's already some code for pruning unnotifiable teams, a similar check for unnotifiable users seems like it'd make sense.

**Comment by dd32** [comment]
Just noting that there's other code in place on dotorg to skip sending emails to blocked members, so prior to this, the emails weren't actually going out.

**Comment by iandunn** [comment]
I think they were, we got several reports. Are you thinking of [blocked _domains_](https://github.com/WordPress/five-for-the-future/issues/212#issuecomment-1370297852) instead?

**Comment by dd32** [comment]
> Are you thinking of https://github.com/WordPress/five-for-the-future/issues/212#issuecomment-1370297852 instead?

Huh.. yeah I am.. The blocked emails from this cron job were indeed from blocked domains..  I had thought we were blocking all emails to the banned accounts but I guess not.
