### ISSUE TITLE
Styling on Report page is off

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#222]
https://wordpress.org/five-for-the-future/report/

![Screenshot 2023-02-03 at 8 49 38 AM](https://user-images.githubusercontent.com/484068/216660211-ac2b620d-78df-4b50-ba95-e590b3da69ae.png)

**Comment by pkevan** [comment]
closing as it looks fine now, and also lacks enough detail to describe what was "off" about it 😄
