### ISSUE TITLE
 Plugin Review Team badge icon is not available. 

### ISSUE THREAD

**Issue by dhrumilkumbhani** [WordPress/five-for-the-future#241]
### The Plugin Review Team badge icon is not available. 
Example URL: https://wordpress.org/five-for-the-future/pledge/hostinger-international/

you can see it here. in the Contributions section, the Plugin Review Team badge icon is not available.

Screen Short: 
![image](https://github.com/WordPress/five-for-the-future/assets/57712674/2691138a-55d0-48a8-93af-a1df7a48622b)

**Comment by dhruvi123456** [comment]
![image](https://github.com/WordPress/five-for-the-future/assets/53272746/01652e60-475d-4f15-a7c2-826eff389e53)

If you will add this 2 class then it will appear fine.
**badge-plugins-reviewer  dashicons-admin-plugins**

**Comment by pkevan** [comment]
Thanks for the report - I'll draft up a PR to fix this shortly.

**Comment by dhrumilkumbhani** [comment]
@pkevan I have created 1 PR for that can you verify it and approve it? and let me know if need any changes.

**Comment by pkevan** [comment]
Thanks! Yes, I just saw the mention when commenting :)

**Comment by pkevan** [comment]
Fixed in #242
