### ISSUE TITLE
Sustainability Team Icon is missing

### ISSUE THREAD

**Issue by keyurptl** [WordPress/five-for-the-future#246]
Sustainability Team Icon is missing in Pledge Company Page

### **Steps to Reproduce:**
- **Go to this page:** https://wordpress.org/five-for-the-future/pledge/automattic/

### **Screenshots:** 
![sustainability-icon-missing](https://github.com/WordPress/five-for-the-future/assets/11974641/68c375f8-4987-40cd-ac51-852444f45b84)

**Comment by jeffpaul** [comment]
Probably same/similar issue as #230
