### ISSUE TITLE
Request: create two report tools for Five for the Future

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/five-for-the-future#248]
Hello there! I'm requesting the creation of two report tools for Five for the Future, similar to [those](https://central.wordcamp.org/wp-admin/index.php?page=wordcamp-reports) on WordCamp Central, to complement the existing information already available [here](https://wordpress.org/five-for-the-future/wp-admin/edit.php?post_type=5ftf_pledge&page=5ftf_stats).

We propose having the following two reports:

- Company Report
- Contributor Report

[Here is the list](https://docs.google.com/spreadsheets/d/1IGTLaAPtzNznsvidIY0pK4yUeiX-789axhJbsTHRFgs/edit?usp=sharing) of data we'd require for each of these reports.

Thanks!

**Comment by courtneyr-dev** [comment]
I would like to include data that encompasses any contribution to Meetups (organizers, speakers, etc) as well as WordCamps, Do_Action, and the like. Speakers, volunteers, organizers, etc. There isn't really activity happening in the community team GitHub about this at this time.  How could we best account for these folks? 

Also, support team with replying to and closing issues in the forums? 

And can we get any info that relates to someone publishing posts? RSS as an author? That would cover a good bit of Make teams.

**Comment by colorful-tones** [comment]
I would love to see some more reports. Those links above only redirect to my WP.org profile. I likely do not have the proper permissions to see them, which makes me even more curious about what they offer.

**Comment by peiraisotta** [comment]
Hi @colorful-tones ! The links above open the following:

- WordCamp Central report tool, accessible to global community program managers and website admins.
- Five for the Future admin page, accessible to all admins of the Five for the Future website.

The community has been discussing about creating a public dashboard for the projects and teams, and I hope that we can take some steps toward that this year.

**Comment by colorful-tones** [comment]
> The community has been discussing about creating a public dashboard for the projects and teams, and I hope that we can take some steps toward that this year.

This is wonderful news! Please let me know if there is anything I can help with to support moving this forward. Thanks!

**Comment by peiraisotta** [comment]
Awesome! I hope that this month we can start another conversation to follow up on the latest feedback gathering happened in September: https://make.wordpress.org/project/2023/09/25/request-for-feedback-make-team-dashboards/ 

I'll ping you so you won't miss it :)

**Comment by patriciabt** [comment]
Yes, so I guess this is the community discussion @StevenDufresne is asking in #201 (latest comment)
([see my comment](https://github.com/WordPress/five-for-the-future/issues/201#issuecomment-2055573107) )
and also related to #176 

And as @courtneyr-dev mentions also events' volunteers, even if we fill their username in the event dashboard (Volunteers CPT), nothing appears on their profile, see the [latest Slack discussion about it](https://wordpress.slack.com/archives/C08M59V3P/p1698920666987479), when @iandunn said "it's just a matter of prioritizing it" (so let's prioritize during the next Contributor Day!)
Related to [that ticket #550 in the WordCamp.org GH repository](https://github.com/WordPress/wordcamp.org/issues/550) (CPT is done now though)

**Comment by peiraisotta** [comment]
Hi! I think that it some additional background could we useful to avoid confusions: This request was for compiling [Five for the Future Program Updates](https://make.wordpress.org/updates/2024/05/23/five-for-the-future-program-updates-may-2024/).

Thanks to the meta team, the first functionality has been added. @pkevan please let me know if we should close this issue or if we need to keep it open until the second request is fulfilled as well. 

For additional ideas, let's start a separate issue or [discussion](https://github.com/WordPress/five-for-the-future/discussions).

**Comment by pkevan** [comment]
> @pkevan please let me know if we should close this issue or if we need to keep it open until the second request is fulfilled as well.

Let's keep it open until the `Contributor Report` is live.

**Comment by peiraisotta** [comment]
Hi @pkevan , I think there is a mistake in the company report. The `Pledge URL` link field is the same of the `Company URL` field instead of having the link to their public 5ftF pledge permalink. Please let me know if you need any additional info on my side to look into this.

**Comment by pkevan** [comment]
> The Pledge URL link field is the same of the Company URL field instead of having the link to their public 5ftF pledge permalink.

I think most don't have a separate pledge URL it's coming from the organisation URL field or do you mean the 5ftf link like: https://wordpress.org/five-for-the-future/pledge/automattic/ which is linked from the `Company` column.

**Comment by peiraisotta** [comment]
I mean the 5ftf link like: https://wordpress.org/five-for-the-future/pledge/automattic/ 

When I download the report, there is no link from the Company column and the columns **pledged url** and **company url** have both the link to the company website.

Here an example: https://docs.google.com/spreadsheets/d/16uKcxtzUXh1sr4fKFMiAFme94D7y3RSlqqpCvpIsZME/edit#gid=1489424981

**Comment by pkevan** [comment]
👍 it won't be possible to add it as a link in a CSV, but it can be added as an additional column.

**Comment by peiraisotta** [comment]
Oh yes, probably I misspoke. I thought that those URL could go under the column pledged url. Whatever the name of the column is, if it contains these urls it would be perfect! If you're going to add an additional column, we are not going to need the **pledged url** column anymore, as it contains the same url of the **Company URL** column.

Thanks a lot!

**Comment by pkevan** [comment]
Closing as initial work has been completed - any follow-up can be done in separate issues.
