### ISSUE TITLE
Pick a textdomain

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#25]
I see `wporg-5ftf`, `wporg`, `wordpressorg`… Which should we be using for this project?

**Comment by iandunn** [comment]
I think we should use one of the existing ones instead of `wporg-5ftf`, to avoid having to setup a new GlotPress project.

`wporg` looks like the most common one used on w.org by far, so I'd vote for that.

**Comment by iandunn** [comment]
🤔 , https://github.com/WordPress/five-for-the-future/pull/19#pullrequestreview-297679747 makes me think that maybe we should just remove the translation calls and leave the strings hardcoded. If we i18n them, translators will have to do work to translate them, but without any benefit, so it'll be wasting their time.

**Comment by ryelle** [comment]
Removing them only to potentially re-add them later seems like extra work (the RTL styles in that PR weren't being correctly generated in the first place). Retrofitting i18n back into untranslated themes is kind of a pain.

If we leave them in, but as a separate project (`wporg-5ftf`), could we communicate that this isn't a project ready for translation? And once we have a process for non-English versions we could either flip back to `wporg` or let translators work on `wporg-5ftf`.

**Comment by coreymckrill** [comment]
If we use `wporg-5ftf` now, which doesn't currently exist as a GlotPress project, would that project get created automatically (and thus translators would start putting time in on it)? Or would we have to manually create the project? If the latter, I like the idea of using `wporg-5ftf` as a "placeholder" text domain. That way we can keep the work we've already done to translate strings without adding more work for polyglots.

**Comment by ryelle** [comment]
Going to continue the convo from #60 here:

> My understanding from #25 was that we weren't going to remove i18n from strings that had already been translated, but I'm not seeing anything there about strings that haven't been translated yet.

We decided to leave translated strings in place, which I read as also using i18n for new strings, so that we stay consistent within our codebase. It's also easier to find strings to change textdomains when they're already using the i18n functions.

Action items as I see it from this issue:

- Update all i18n functions to use `wporg-5ftf` as textdomain, which can be easily found with [phpcs's `text_domain` rule setting.](https://github.com/WordPress/five-for-the-future/blob/67958d9a1a7bd9d4ec1dc19171f566a6a9cf103b/phpcs.xml.dist#L146)
- Find all untranslated strings and wrap them in the correct i18n calls

**Comment by iandunn** [comment]
It seems like the rationale for leaving them was [avoiding extra work](https://github.com/WordPress/five-for-the-future/issues/25#issuecomment-541226024), but it feels doing it for new strings would be _adding_ extra work.

> Internationalizing new strings in advance feels like wasted time/energy to me, since we don't have any plans to build a localized version of the site, and I don't see us even thinking about it any time in the next year or two. If we do though, we can always come back and add it when we're not under a tight deadline. It seems like the same amount of work either way, but it's likely that we'll never actually use it, so it seems best to me to wait until we have an actual plan for it.

**Comment by ryelle** [comment]
I guess we have different approaches– I'm so used to internationalizing by default that it's just second nature, not "extra work".

I also see it as little-to-no extra work while developing the theme, to save us the effort of going back over things later – as this site is surely not going to be English-only forever. Rather than have to spend 10hrs later going through every file to make sure it's all translated, we can just use the i18n functions now.

**Comment by iandunn** [comment]
I don't see how it's going to take 10 hours to do later, but it's so little work if we do it now that it's inconsequential?

>  as this site is surely not going to be English-only forever.

That _might_ be a safe assumption about the primary sections of w.org -- which would be great, FTR -- but even that isn't on the horizon; and this particular section is still in the experimental phase.

But yeah, I think we just have different approaches.  Happy to disagree and commit if Corey feels like it's worth the extra work go back and update all of them.

**Comment by coreymckrill** [comment]
I think we should be consistent and keep everything localizable (with the possible exception of [logs](https://github.com/WordPress/five-for-the-future/pull/54) since those are strings that get stored in the database). I don't think it needs to happen during our current milestones, though. Let's just keep this issue open and we can try to get it resolved during the [Manage a Pledge](https://github.com/WordPress/five-for-the-future/milestone/2) milestone

**Comment by ryelle** [comment]
Sounds like the decision is made here, so I'm untagging this from "Needs Decision" and the action that should happen is:

- Audit all user-facing strings and add translation calls where needed
- We should use the `wporg-5ftf` text domain
