### ISSUE TITLE
Implementation details for #248

### ISSUE THREAD

**Issue by pkevan** [WordPress/five-for-the-future#250]
Pulling out some implementation details from: #248 so as to not derail that discussion.

- How is the expected report look to be configured? CSV download, web page report?
- Is there any filtering?
- What user level are we restricting to access this? Presumably administrator, like the others
- Is there any expectation of a public facing i.e. no restriction report, and if so, are there any fields which should be private or restricted to certain user levels?

cc @peiraisotta

**Comment by harishankerr** [comment]
@pkevan 👋  Thank you so much for looking into this! Happy to answer your questions:

- CSV download would be perfect in this case.
- Having a date filter would be nice, in this case.
- For this report, administrator access would be sufficient.
- Short answer: Right now, we don't need a public-facing report.
More context:  We have discussed creating a public-facing report, and it would be surely be needed at some point. However, a lot more thought needs to be put into that, and might probably work best with the dashboard project.

**Comment by pkevan** [comment]
Thanks @harishankerr - i'm going to get the Company report done first, with the easiest data in there - i've come across a few complications when looking at this initially.

**Comment by harishankerr** [comment]
That sounds excellent, @pkevan! Thank you so much!

**Comment by pkevan** [comment]
Closing as completed, any follow-up can go in individual issues.
