### ISSUE TITLE
Update PHPCS runner

### ISSUE THREAD

**Issue by pkevan** [WordPress/five-for-the-future#253]
Currently the PHPCS feedback on PRs is virtually unusable, since it doesn't really indicate where the issue is within the code, so you have to guess where to alter things!

![Screenshot 2024-05-21 at 12 31 56](https://github.com/WordPress/five-for-the-future/assets/2290623/2c6561c1-5d62-48ea-b5f9-bc9ce07a23c4)

![Screenshot 2024-05-21 at 12 32 15](https://github.com/WordPress/five-for-the-future/assets/2290623/aebf987a-8118-4d35-9cb9-c574af8f0aea)

It appears like the methods used across repos aren't consistent, so that's probably a good place to start.

Example is from: https://github.com/WordPress/wordcamp.org

**Comment by courtneyr-dev** [comment]
Can you elaborate on the connection to this repo a bit more?

**Comment by pkevan** [comment]
The output is from: https://github.com/WordPress/five-for-the-future/actions/runs/9173862561/job/25223445480?pr=252 vs https://github.com/WordPress/wordcamp.org/actions/runs/8994333684/job/24707633432, and it's due to how the github workflow is setup.

https://github.com/WordPress/five-for-the-future/blob/production/.github/workflows/ci.yml#L46-L51 

against

https://github.com/WordPress/wordcamp.org/blob/production/.github/workflows/linter.yml#L48-L50

**Comment by courtneyr-dev** [comment]
OH! Gotcha. Thanks for the connection :)

**Comment by pkevan** [comment]
Reconsidering this, since the output is accessible inline on the PR, so closing.
