### ISSUE TITLE
WordPress.org user management

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#26]
_[moving from code comment to github issue]_

> maybe set the wporg username as the company author, so they can edit it themselves to keep it updated, then make the user a contributor if they don't already have a role on the site

**Comment by ryelle** [comment]
I think we decided against this idea, which is why we're using the email + one-time password system, but I wanted to flag it before just removing the comment.

**Comment by coreymckrill** [comment]
Yep, it's fine to remove the comment.

**Comment by iandunn** [comment]
Related: #51
