### ISSUE TITLE
Visual inconsistency for one of the link present on 5FTF handbook page

### ISSUE THREAD

**Issue by kjnanda** [WordPress/five-for-the-future#260]
**Description:** 
There seems to be an issue with the links' actual and hover state. There are multiple links on this page but only one link seems to have a issue with visual effect.

**Where is the issue present?**

https://wordpress.org/five-for-the-future/handbook/

**Link with which the issue seems:**

[Contribution Best Practices for Organizations](https://wordpress.org/five-for-the-future/handbook/organization-pledge-guide/best-practices)

-----

**Normal State Visual Difference** 

<kbd>![Screenshot](https://github.com/WordPress/five-for-the-future/assets/15173772/0ba3541c-c8cd-405e-80aa-02f89372c350)</kbd>

-----

| **Expected - Hover Link State** | **Actual - Hover Link State** | 
|----|----|
| ![a](https://github.com/WordPress/five-for-the-future/assets/15173772/bb902478-9f58-4d79-82d7-ea755ad9b826) | ![eh](https://github.com/WordPress/five-for-the-future/assets/15173772/c995f14e-c5d8-46d1-a2a0-736de10a9f47) |

**Comment by ryelle** [comment]
I've fixed the markup on this page so the links all have consistent hover/focus states.
