### ISSUE TITLE
Update: Individual Contributors page content outdated.

### ISSUE THREAD

**Issue by richardmorrison** [WordPress/five-for-the-future#271]
Following the instructions on the "Contribute as an Individual" page shows incorrect screenshots, and possibly links.
This could be causing some confusing for users wanting to contribute.

Login link redirects (me) to the home of WordPress.org (in Chrome, though correct in other browsers)

**Header Links:**
Location of the header links on https://profiles.wordpress.org/me/ show not in a dropdown.
Screenshot:
https://wordpress.org/five-for-the-future/files/2023/11/wp-header-login-2048x208.png
![wp-header-login-2048x208](https://github.com/user-attachments/assets/2664a487-19e2-497d-ab01-7452a26a97e5)
vs
Current:
<img width="1006" alt="Screenshot 2024-07-30 at 11 39 37 AM" src="https://github.com/user-attachments/assets/e7f44735-b23d-4a30-a81e-034f425bf96a">

**Profile Links:**
Edit Profile links shows lower in the Profile now:
Screenshot:
https://wordpress.org/five-for-the-future/files/2023/11/edit-wp-profile.png
<img width="306" alt="edit-wp-profile" src="https://github.com/user-attachments/assets/eea36571-389b-42c0-8cb0-591b12187140">
vs
Current:
<img width="347" alt="Screenshot 2024-07-30 at 11 41 06 AM" src="https://github.com/user-attachments/assets/afa3f71b-9629-4d8e-a911-9b8516c3c254">

**Contributions Link:**
Contributions Page link is now: https://profiles.wordpress.org/me/profile/edit/group/5/
Screenshot:
https://wordpress.org/five-for-the-future/files/2023/11/wp-profile-contribution.png
<img width="802" alt="wp-profile-contribution" src="https://github.com/user-attachments/assets/984cfa32-2224-498d-bac6-543a1a75f586">
vs
Current:
<img width="1006" alt="Screenshot 2024-07-30 at 11 43 17 AM" src="https://github.com/user-attachments/assets/1e109ba8-a306-463f-af39-454bc50bbdda">

Note: It would also be nice if this page linked or shared more direct ways to contribute, rather than just to "Pledge", which feels misleading from the page title.

URL: https://wordpress.org/five-for-the-future/for-individuals/

**Comment by ndiego** [comment]
I have updated the screenshots with the ones provided by @fcoveram [here](https://www.figma.com/design/cwsZHx6NpLnFhuzKaco7Jq/Five-For-the-Future?node-id=1611-5159&node-type=section&m=dev). This page will be updated once the refresh is launched tomorrow, so I am closing this issue out as completed. 

![wordpress org_five-for-the-future-test_for-individuals_ (1)](https://github.com/user-attachments/assets/15612a90-5f2b-4ab9-98e8-35484a9495d1)
