### ISSUE TITLE
New Theme: Report a problem/Edit Pledge button alignment.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#277]
The `Report a problem` link is misaligned because it has button padding. 

Can we either make it appear like button or not use the button component?

## Screenshot

<img width="329" alt="Screenshot 2024-09-03 at 9 09 27 AM" src="https://github.com/user-attachments/assets/4dd80f7a-00ed-481c-a627-afd0a5bcb460">

**Comment by ndiego** [comment]
I wonder if these could just be links in a Row block?

**Comment by ryelle** [comment]
The first button could be a plain link sure, the second isn't a link, so it needs the button style.

**Comment by ndiego** [comment]
> The first button could be a plain link sure, the second isn't a link, so it needs the button style.

Oh right, that's the modal...

**Comment by ryelle** [comment]
So, links in content have underlines, which looks a little strange next to the not-underlined button, but if this looks okay otherwise I can make this change:

![Image](https://github.com/user-attachments/assets/1a183ed3-dfbc-4e13-b428-27eb7b33e865)

**Comment by StevenDufresne** [comment]
Based on [my understanding of Use of Color](https://github.com/WordPress/wordpress.org/issues/262), "Edit Pledge" needs to be underlined or distinguished more clearly.

**Comment by ryelle** [comment]
It does, but we've been skirting that with the text-style buttons. We could make both of them outlined buttons, which should pass use of color.

**Comment by fcoveram** [comment]
> We could make both of them outlined buttons, which should pass use of color.

I like this idea. I will update the mockup to reflect the change
