### ISSUE TITLE
New Theme: Improve pledge mobile layout.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#279]
Can we improve the mobile view for https://wordpress.org/five-for-the-future-test/pledges/?

**Suggested Improvements**
 - Add more spacing between companies
 - Extend the image container full width
 - Reduce the size of the company image to `200px` on smaller views.

| Test Site | Proposed |
|--------|--------|
| ![wordpress org_five-for-the-future-test_pledges_ (2)](https://github.com/user-attachments/assets/8bf65a63-23c7-4704-a4a5-22f76ade0237) | ![wordpress org_five-for-the-future-test_pledges_ (3)](https://github.com/user-attachments/assets/da4de077-f59b-4808-9a62-0df17f7f24db) |

**Comment by ndiego** [comment]
I like the proposed approach. What do you think @WordPress/meta-design?

**Comment by fcoveram** [comment]
I added a new [section](https://www.figma.com/design/cwsZHx6NpLnFhuzKaco7Jq/Five-For-the-Future?node-id=1345-5297&node-type=SECTION&m=dev) in the Design page with mobile mockups, and @StevenDufresne's proposal matches with [the one](https://www.figma.com/design/cwsZHx6NpLnFhuzKaco7Jq/Five-For-the-Future?node-id=1345-4363&node-type=FRAME&m=dev) I added.

Here is a screenshot.

<img alt="Mockup of pledges page on mobile" src=https://github.com/user-attachments/assets/7bbbdb05-6365-406e-9213-c2e1dd777468 width=300>
