### ISSUE TITLE
New Theme: Missing `<h2>` heading on contribute pages.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#281]
On https://wordpress.org/five-for-the-future-test/for-organizations/ and https://wordpress.org/five-for-the-future-test/for-individuals/, we go from `<h1>` to `<h3>`.

<img width="343" alt="Screenshot 2024-09-03 at 9 38 39 AM" src="https://github.com/user-attachments/assets/2a8644b5-7c20-42e9-aff7-43d5ee8d0c84">
<img width="344" alt="Screenshot 2024-09-03 at 9 38 34 AM" src="https://github.com/user-attachments/assets/3688cc93-f884-4d00-bc93-6fb84cd205a3">

**Comment by ryelle** [comment]
Fixed in the page content.
