### ISSUE TITLE
New Theme: External link requires external link indicator.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#282]
On `five-for-the-future-test/pledge/{company name}/`, the company url should have an external link indicator.

| Test Site | Proposed |
|--------|--------|
| <img width="965" alt="Screenshot 2024-09-03 at 9 45 08 AM" src="https://github.com/user-attachments/assets/bcf39c40-2f55-4eff-aa26-542f333c5efc"> | <img width="1018" alt="Screenshot 2024-09-03 at 9 45 01 AM" src="https://github.com/user-attachments/assets/3dba0b33-aae4-40e3-a7f0-02404a16fa70"> |

**Comment by ryelle** [comment]
This is not in the design. I think it's understood that it's an external link given the context, but if we're strict about the icon I can add it. Thoughts @fcoveram?

<img width="525" alt="Screenshot 2024-09-03 at 10 10 41 AM" src="https://github.com/user-attachments/assets/98519ed1-8120-4367-8089-ca12b6b04c8a">

**Comment by fcoveram** [comment]
I agree with @StevenDufresne. I will update the mockups by adding the icon.

**Comment by StevenDufresne** [comment]
Noting that external links indicated as such is a requirement for all links on wp.org (requested by Matt).
