### ISSUE TITLE
New Theme: "Contributors" title on pledge page too big.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#283]
The "Contributors" heading on a pledge page should match the headings in other directories ([example](https://wordpress.org/themes/hello-elementor/)) which use `var(--wp--preset--font-size--large) !important`

| Test Site | Proposed |
|--------|--------|
| <img width="436" alt="Screenshot 2024-09-03 at 9 53 20 AM" src="https://github.com/user-attachments/assets/2b3145a1-3780-477e-8d9e-756d5088b86b">  | <img width="446" alt="Screenshot 2024-09-03 at 9 54 40 AM" src="https://github.com/user-attachments/assets/38876e44-5552-4e37-bc23-103a9953e59e"> |

**Comment by ryelle** [comment]
There was also some discussion about [which heading size set to use](https://github.com/WordPress/five-for-the-future/issues/274#issuecomment-2326608699), and changing to the Inter set might help with this.
