### ISSUE TITLE
New Theme: The font size for the Make team labels is a bit small

### ISSUE THREAD

**Issue by ndiego** [WordPress/five-for-the-future#284]
The Staging site matches the font size in [Figma](https://www.figma.com/design/cwsZHx6NpLnFhuzKaco7Jq/Five-For-the-Future?node-id=1145-4212&node-type=TEXT&m=dev), but it feels too small on the live site. I think we should bump it up from `--wp--preset--font-size--extra-small` to `--wp--preset--font-size--small`.

| Current (`extra-small`) | Proposed (`small`) |
|-|-|
|<img width="518" alt="image" src="https://github.com/user-attachments/assets/af4401ae-8eb8-4150-8733-8130f44e9c92">|<img width="525" alt="image" src="https://github.com/user-attachments/assets/9188788e-c909-4dc2-9cf6-1ace452855df">|

_Ignore the "Documentation Team" label in the second screenshot, I was just testing what a longer label would look like._

**Comment by fcoveram** [comment]
I second this idea ✨
