### ISSUE TITLE
New Theme: Update company pledge hours copy on Pledge page

### ISSUE THREAD

**Issue by thetinyl** [WordPress/five-for-the-future#285]
The new design currently leverages the old theme's language for company pledge hours:

<img width="504" alt="image" src="https://github.com/user-attachments/assets/77c1c77b-e772-4df0-9d69-48fac4086fbb">

Let's update that copy to read:

> [COMPANY NAME]
> pledges [###] hours a week

This makes the pledge feel more like an ongoing commitment and flows more seamlessly from the company name vs. treating it as its own sentence fragment.

**Comment by ndiego** [comment]
Sounds good!

**Comment by ryelle** [comment]
Just a note, and we don't need to worry about this yet (since this site isn't translated), but for languages that change word order, this doesn't quite work out as a full sentence — if/when we start translating, this will need a rethink.
