### ISSUE TITLE
Remove gray border on org profile images and pledge images

### ISSUE THREAD

**Issue by fcoveram** [WordPress/five-for-the-future#289]
URL where issue is: https://wordpress.org/five-for-the-future-test/pledge/los-pepinos-de-pullally/

Browser you're using: Arc v1.57.2

## What do you see?

In the page header area, the org profile image has a gray border that is not used in any other place

<img src=https://github.com/user-attachments/assets/187fe6e0-c2e5-4466-88c6-7c696497afca alt="Screenshot of header area in org profile page" width=450>

## What should be changed?

Remove the border to make it look like in the pledges list

**Comment by ndiego** [comment]
@fcoveram it looks like the pledges list has the same border. This should be removed as well, right? 

<img width="1395" alt="image" src="https://github.com/user-attachments/assets/9827f430-fe0c-4700-93b4-fcc5972c5cf7">

**Comment by fcoveram** [comment]
Yes! Thanks for noticing it.
