### ISSUE TITLE
Profiles: Show pledge(s) you contribute to on your profile

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#29]
We want to show the pledges you contribute to on your `profiles.w.org` profile. This will also show a "remove" button, which will link the user over to a page on Five for the Future for managing pledges.

**Comment by melchoyce** [comment]
So, more than just the "sponsored" I previously scoped out with Andrea?

![image](https://user-images.githubusercontent.com/2846578/66610243-077a1900-eb89-11e9-943e-f06fedf28f18.png)

**Comment by ryelle** [comment]
We talked about showing the pledge names (companies) here, but realistically all this needs is an edit link to direct you to the page you designed in https://github.com/WordPress/five-for-the-future/issues/30 – like this, but with the right font/color/etc…

![66610243-077a1900-eb89-11e9-943e-f06fedf28f18](https://user-images.githubusercontent.com/541093/66666413-908f5f80-ec1e-11e9-961f-a9a81528c6af.png)

**Comment by melchoyce** [comment]
How's this?

![image](https://user-images.githubusercontent.com/2846578/66667233-8ec69b80-ec20-11e9-88f1-78d0830f8534.png)

https://www.figma.com/file/8IoAXoJC6cPgx2Gm2YChxK/WordPress.org-Profiles?node-id=0%3A35

**Comment by ryelle** [comment]
That works, thanks!

**Comment by coreymckrill** [comment]
I was actually thinking that the list of pledges and the`Edit` buttons would be on the profile edit screen, not necessarily on the public-facing side. Something like this:

![edit-profile-contribution](https://user-images.githubusercontent.com/916023/66789544-1da21500-eeba-11e9-99ba-f232b8a07cd5.jpg)

**Comment by iandunn** [comment]
This might already be implied, but if it's on the user-facing side, I think it should only appear to the profile owner when they're logged in.

**Comment by iandunn** [comment]
Related discussion: https://github.com/WordPress/five-for-the-future/issues/10#issuecomment-546455108, which then moved to #51. This issue is probably still the best place to discuss the UI aspects, though.

**Comment by coreymckrill** [comment]
This is done via the following commits:

* dotorg r15488
* dotorg r15489
* dotorg r15490
