### ISSUE TITLE
Gap in pledge list is too tight on mobile

### ISSUE THREAD

**Issue by fcoveram** [WordPress/five-for-the-future#290]
URL where issue is: https://wordpress.org/five-for-the-future-test/pledges/

Browser you're using: Arc v1.57.2

## What do you see?

The spacing between the `li` elements in the pledge list is too small and makes the layout look tight. Here is a screenshot where the gap below the profile image is the space I'm referring to.

<img src=https://github.com/user-attachments/assets/d7c579e0-538f-4c5a-b694-cbbd0f61c833 alt="Screenshot of pledges list. Area of space between pledges" width=300>

## What should be changed?

The margin value is correct (`var(--wp--preset--spacing--60)`) and looks great on desktop, but I wonder if there is a variable with a minimum value of `40px` or similar to give more space when items stack.

**Comment by wandson88** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by ndiego** [comment]
Similar to #280, I think we can switch out `--wp--preset--spacing--60` with `--wp--preset--spacing--50`

**Comment by fcoveram** [comment]
Great idea. +1
