### ISSUE TITLE
Make company name link to respective pledge on Testimonials page

### ISSUE THREAD

**Issue by thetinyl** [WordPress/five-for-the-future#293]
## What do you see?
The [Testimonials page](https://wordpress.org/five-for-the-future-test/testimonials/) includes 'Sponsored by [COMPANY]' copy beneath the featured contributors' names. 
<img width="738" alt="image" src="https://github.com/user-attachments/assets/a44c6274-fe47-452f-8d42-63257930620f">

## What should be changed?
Let's link the company name to their respective pledge pages. This will benefit the company by recognizing its contributors and letting prospective contributors learn more about the company's involvement with the project.

**Comment by ndiego** [comment]
I have updated this here: https://wordpress.org/five-for-the-future-test/testimonials/ @ryelle I am not sure how to add the external icon. Is this a class?

**Comment by thetinyl** [comment]
Oh, sorry if this wasn't clear, I meant to link to the company pledge pages on .org (example: https://wordpress.org/five-for-the-future/pledge/xwp/), not the company's site.

**Comment by ndiego** [comment]
> Oh, sorry if this wasn't clear, I meant to link to the company pledge pages on .org (example: https://wordpress.org/five-for-the-future/pledge/xwp/), not the company's site.

Ah, that makes more sense 🤦‍♂️ 

All fixed.
