### ISSUE TITLE
Update 'Learn more' link copy on Testimonials page

### ISSUE THREAD

**Issue by thetinyl** [WordPress/five-for-the-future#294]
URL for reference: https://wordpress.org/five-for-the-future-test/testimonials/

## What do you see?
Visitors to the testimonials page can navigate to the featured contributors' WP.org profiles by way of a 'Learn more' link. I think the current copy can be finessed to be clearer about what a visitor will find there. 

<img width="678" alt="image" src="https://github.com/user-attachments/assets/89096f9c-4ccc-4030-943a-1431e797f2bb">

## What should be changed?

I suggest updating the current copy and replacing it with:

> Follow [CONTRIBUTOR NAME]'s latest contributions

**Comment by ndiego** [comment]
All set: https://wordpress.org/five-for-the-future-test/testimonials/
