### ISSUE TITLE
Home page: Inconsistent layout of Contributor Experiences section on tablet

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/five-for-the-future#296]
Some images go full width, some don't. Could be the media upload.

Unsure if the text should be inset, or be aligned with the image.

<img src="https://github.com/user-attachments/assets/9fd1ec3a-9fb6-4b13-94f6-bdb2d765e4a7" width="600">

**Comment by ryelle** [comment]
It looks like that one image is too small for the one-column layout, in fact all 3 are small — for high-dpi screens, these should be around 1480px wide. It looks like the images in the mockup are different too, if those can be exported they might be large enough to look better.
 
@ndiego @fcoveram There are currently two versions of the homepage testimonials, which is the correct one? I'll add that the mid-sized screen view of the second version looks better, since it doesn't need super large images.

![Screen Shot 2024-09-09 at 11 21 08](https://github.com/user-attachments/assets/d5268fc9-9527-4a4b-8e47-aa33fb98534a)

![Screen Shot 2024-09-09 at 11 23 06](https://github.com/user-attachments/assets/833d85ec-23d6-4a1c-9d1f-2e122a01b1dc)

**Comment by fcoveram** [comment]
> …which is the correct one? I'll add that the mid-sized screen view of the second version looks better

The version with rounded images is the correct layout, but the images are not. The ones in the mockup are the right ones, provided and approved by the testimonials individuals.

---

The designs were updated in the following way:
* "Homepage" and "Testimonials" mockups (desktop and mobile) have the new layout and correct photos.
* [Testimonials](https://www.figma.com/design/cwsZHx6NpLnFhuzKaco7Jq/Five-For-the-Future?node-id=1417-4137&node-type=SECTION&m=dev) page on desktop now reuses the layout of "Contribute as an Individual" as it fits better with the rounded image next to the individual info.
* [Testimonial photos](https://www.figma.com/design/cwsZHx6NpLnFhuzKaco7Jq/Five-For-the-Future?node-id=1477-5232&node-type=SECTION&m=dev) section was updated with high-res images.

Please let me know if everything is clear.

**Comment by ndiego** [comment]
> The designs were updated in the following way:
> "Homepage" and "Testimonials" mockups (desktop and mobile) have the new layout and correct photos.
[Testimonials](https://www.figma.com/design/cwsZHx6NpLnFhuzKaco7Jq/Five-For-the-Future?node-id=1417-4137&node-type=SECTION&m=dev) page on desktop now reuses the layout of "Contribute as an Individual" as it fits better with the rounded image next to the individual info.
[Testimonial photos](https://www.figma.com/design/cwsZHx6NpLnFhuzKaco7Jq/Five-For-the-Future?node-id=1477-5232&node-type=SECTION&m=dev) section was updated with high-res images.
Please let me know if everything is clear.

I have made all these changes. @ryelle, we will just need to reset the Page Title alignment on the Testimonials page template. Let me know if you see anything that's incorrect @fcoveram on the staging site: https://wordpress.org/five-for-the-future-test/

<img width="1105" alt="image" src="https://github.com/user-attachments/assets/96572755-59a2-4e9a-bd54-1b5c3d508e44">

**Comment by ryelle** [comment]
> I have made all these changes. @ryelle, we will just need to reset the Page Title alignment on the Testimonials page template. Let me know if you see anything that's incorrect @fcoveram on the staging site: https://wordpress.org/five-for-the-future-test/

To confirm, the page is no longer wide-width?

**Comment by ndiego** [comment]
> To confirm, the page is no longer wide-width?

Correct. We decided to make the contributor images smaller on the homepage, more like avatars. So this updated the Testimonials design as well. @fcoveram updated the [design here](https://www.figma.com/design/cwsZHx6NpLnFhuzKaco7Jq/Five-For-the-Future?node-id=1417-4137&node-type=section&t=xT1DXz2TBZquKGnk-0). Sorry for the back and forth.

**Comment by ryelle** [comment]
@ndiego Can we use smaller images for Milana and Nadia? The images are displayed at 100px, but the homepage is currently loading 1200px wide images for them. I can optimize/resize the images if the core settings don't work well here.

**Comment by ndiego** [comment]
> @ndiego Can we use smaller images for Milana and Nadia? The images are displayed at 100px, but the homepage is currently loading 1200px wide images for them. I can optimize/resize the images if the core settings don't work well here.

Yeah, I will take care of it later today. I'll follow up once complete.

**Comment by ryelle** [comment]
Great, I'll assign this issue to you and mark it in progress. The testimonial page is a separate issue, I've created it here https://github.com/WordPress/five-for-the-future/issues/302

**Comment by ndiego** [comment]
All the images have been updated.
