### ISSUE TITLE
Contributors: Let contributors remove themselves from pledge

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#30]
After clicking the "remove" link from #29, the user will end up on a page on Five for the Future with all pledges they are connected to (since they're logged in, we know who they are). Most people will only be connected to one pledge, probably?

Each pledge on the page should also have a "remove me" button, which will remove that contributor from the pledge.

**Comment by melchoyce** [comment]
Will the first example be a totally new page?

**Comment by melchoyce** [comment]
![image](https://user-images.githubusercontent.com/2846578/66605985-1fe53600-eb7f-11e9-8328-d7fe4022b582.png)

[All the various states can be found on Figma](https://www.figma.com/file/OirvZ8jLK3CNzVHnmAYjbufc/Five-for-the-Future?node-id=662%3A385).
