### ISSUE TITLE
Aspect ratio of org logo

### ISSUE THREAD

**Issue by fcoveram** [WordPress/five-for-the-future#301]
URL where issue is:
* Pledges: https://wordpress.org/five-for-the-future-test/pledges/
* Organization pledge: example https://wordpress.org/five-for-the-future-test/pledge/automattic/
* My Pledges: https://wordpress.org/five-for-the-future-test/my-pledges/

Browser you're using: Arc 1.59.0

## What do you see?

On mobile, "Pledges" and "My pledges" pages show the org logo as an image not reaching the container's width.

| Pledges | My pledges |
|:---|:---|
| ![Screenshot of pledges page on mobile](https://github.com/user-attachments/assets/f916763b-ff93-47ac-a7e4-9b9625dda975) | ![Screenshot of my pledges page on mobile](https://github.com/user-attachments/assets/d85ff75e-4295-4341-8e4b-46e2fe5e8b20) |

Meanwhile, the organization pledge page shows the image in a horizontal layout.

<img src=https://github.com/user-attachments/assets/121055d3-4415-4bc4-aaac-22b9ad22cf4c alt="screenshot of automattic company's pledge on mobile" width=300>

## What should be changed?

Three things can improve the layout:
* Show the image in full-width.
* Apply an aspect ratio of 16:9 to the container.
* Apply `light-grey-2` color to the container's background (if it hasn't been applied yet).

Here is a screenshot of the mockups on mobile documented in [the designs](https://www.figma.com/design/cwsZHx6NpLnFhuzKaco7Jq/Five-For-the-Future?node-id=1345-5297&node-type=SECTION&m=dev).

![CleanShot 2024-09-09 at 18 34 14@2x](https://github.com/user-attachments/assets/7b802a98-d509-494b-8cd2-8c17019e8aaf)

**Comment by ryelle** [comment]
@fcoveram Can the aspect ratio stay consistent on all screen sizes? So if we're changing to 16:9, it would be 16:9 on desktop too. It's a block setting, so we can't easily change that on different screen sizes (we _can_ hack CSS around it, I'd just prefer not to).

The pledge lists and single pledge page are currently different — with pledge lists as 4:3, and single pledge as 1:1. Just double-checking that you mean to change them all to the same value.

> Apply light-grey-2 color to the container's background (if it hasn't been applied yet).

Can you please check the test site to confirm this?

**Comment by fcoveram** [comment]
> Can the aspect ratio stay consistent on all screen sizes? So if we're changing to 16:9, it would be 16:9 on desktop too.

Sure! Let's apply 16:9 to everything.

> Just double-checking that you mean to change them all to the same value.

Yes. It applies to all pages mentioned in the initial comment

> Can you please check the test site to confirm this?

It looks correctly now.

I noticed that `light-grey-2` has a value of `rgb(246, 246, 246)` instead of `rgb(247, 247, 247)` But that has nothing to do with this report and can be address in the future. The difference is subtle.

**Comment by ryelle** [comment]
> Sure! Let's apply 16:9 to everything.

Great, I'll do that today.

> I noticed that light-grey-2 has a value of rgb(246, 246, 246) instead of rgb(247, 247, 247) But that has nothing to do with this report and can be address in the future. The difference is subtle.

Hm, the variable has the same value as the design library: `#f6f6f6`, and when I switch that to rgb I see `rgb(246, 246, 246)`.

<img width="222" alt="Screenshot 2024-09-10 at 10 14 32 AM" src="https://github.com/user-attachments/assets/ecd2b594-c861-4233-8a6d-767d7155c575">

Aha, it looks like this background color is a custom value, it's not using "Foundational/WP.org Light Grey 2". So the site is correct, but the mockup is not using the shared color.

<img width="310" alt="Screenshot 2024-09-10 at 10 16 41 AM" src="https://github.com/user-attachments/assets/f303ebef-9823-4336-b177-c352077bac89">

**Comment by ryelle** [comment]
If we need to follow up on the color difference, please create a new issue.

**Comment by fcoveram** [comment]
I identified the problem. It's a Figma bug where the library file shows a different color in the files where it's used. Very strange.

No change is needed, `#f6f6f6` is the right color.
