### ISSUE TITLE
Default opengraph image

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#304]
@WordPress/meta-design 

We need an opengraph image for Five for the Future, for example the Theme Directory image: https://wordpress.org/files/2024/06/wporg-themes-ogimage-2024.png

Currently, the site just uses the community photo:

![Image](https://github.com/user-attachments/assets/8abf0776-9934-407c-b9d6-f4b371f87520)

And for individual pledges, it uses the company logo, ex:

![](https://github.com/user-attachments/assets/df81e398-e1b7-45cb-87e9-dac556e168a1)

It would be really neat if we could do dynamic images with the company logo, but our only option for that is [Jetpack's Social Image Generator which only has a few templates](https://jetpack.com/support/jetpack-social/jetpack-social-image-generator/). Since that's not possible right now, should this be left as the company logo?

**Comment by ndiego** [comment]
@fcoveram fyi

**Comment by thetinyl** [comment]
I know this isn't Opengraph image-related, but can we do anything dynamic about the meta tags? 

![Image](https://github.com/user-attachments/assets/ac068196-9aa6-4388-a249-39284d435bfb)

**Comment by ryelle** [comment]
yeah, I'm working on that now — I've updated the pledge page to use the title "Company Name | Five for the Future" and the content is an excerpt of the organization description. For example, Automattic updated:

<img width="520" alt="Screenshot 2024-09-10 at 2 49 46 PM" src="https://github.com/user-attachments/assets/c0314bf5-d2cf-4768-aeb0-cdeb6d9b2d88">

Does that work? or would you rather have different text? I could see either of these working well too:

- Automattic contributes 5% of their resources to the WordPress project.
- Automattic sponsors 105 contributors for a total of 3,799 hours per week across 22 teams.

**Comment by thetinyl** [comment]
Oh, great! Thanks for always being eleventy-eight steps ahead, Kelly. 🥇 

> "Company Name | Five for the Future"

This works for me!

> Automattic contributes 5% of their resources to the WordPress project.
> Automattic sponsors 105 contributors for a total of 3,799 hours per week across 22 teams.

Nothing wrong with either of these. I do wonder about smaller orgs and whether or not those factual stats would be as impressive a flex (if you will). Or, for the outside FftF/contributor audience, do those numbers resonate without context?

I think the description could be a call to action that speaks to the mission of the program in some way... which actually ends up being more generic. Options:

- Find out how Automattic is shaping the future of WordPress. 
- Learn about Automattic’s commitment to shaping the future of WordPress.

**Comment by jasmussen** [comment]
There's an opengraph template we can use [here](https://www.figma.com/design/nK6LcMOZMtRAQdIky3PNIA/Showcase?node-id=4686-24180&t=ttdm4LpPWP4fBkrE-1). I think there are newer templates too, when Francisco has a chance to look he may have better instincts. I've also been reminded that I think there exists a Five for the Future logo that we may be able to work in. @henriqueiamarino may know more.

**Comment by fcoveram** [comment]
[This is](https://www.figma.com/design/wgwqNZTmYbvtC5LMG1XTVC/Open-Graph%E2%80%A8images---Scratchpad-file?node-id=1001-403&node-type=canvas&t=fg7D7HxNBQ8Ffi9c-0) the template file where I've been working on. Here below you can see a recap of all the images made for the site.

![Opengraph images of the WordPress.org site in a board](https://github.com/user-attachments/assets/bd876e68-bed9-4f91-af64-0a6a0620411e)

The file is still WIP so more changes are to come with regard to brand and internationalization ([wporg-mu-plugins#631](https://github.com/WordPress/wporg-mu-plugins/issues/631))

---

Based on the above, here are two ideas for the 5ftF's homepage.

![Two versions of the opengraph image for "Five for the Future" section in WordPress.org site](https://github.com/user-attachments/assets/0a38fc90-df04-4deb-b5dc-a1f665f1be32)

The left one feels cleaner and has room for describing what the section is about. Whereas the right one has more context thanks to the "WordPress" word. If we go with the left one, I would need you help @thetinyl with copy for the description sentence.

**Comment by thetinyl** [comment]
> Whereas the right one has more context thanks to the "WordPress" word.

Based on the template, it looks like there's a preference for having the title+subcopy combo. Which I'd usually want to be consistent with, but I think the right one will be the stronger choice. 

'Five for the Future' as a named program isn't recognizable without the brand affinity of WordPress. Assuming folks won't read the subcopy (😢), we need to make that connection clear as quickly as possible.

**Comment by ndiego** [comment]
I like:

> Find out how Automattic is shaping the future of WordPress.

**Comment by fcoveram** [comment]
Here is the final opengraph image.

![Five for the Future opengraph image](https://github.com/user-attachments/assets/362ef3e9-a6c9-4ebc-9164-4cbdb5e4d687)
