### ISSUE TITLE
Handbooks: Update content to match new templates

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#306]
I've created the template for Handbook pages, but the content itself needs to be updated after launch (since this content is only available on the live site).

In a brief look, each page should be updated to…

- Remove the drop cap
- Remove the pagination from the content (it's in the template)
- Remove the reusable block table of contents ([moved to chapter list](https://github.com/WordPress/wporg-mu-plugins/pull/650))
- Update the notice blocks to use "Notice", not "Callout" (for the redesign style & icons)

![Screen Shot 2024-09-10 at 17 00 56-fullpage](https://github.com/user-attachments/assets/7438d82d-3dbb-4ac3-ad9d-9024329953df)

![Screen Shot 2024-09-10 at 17 01 40](https://github.com/user-attachments/assets/6a83c573-da53-4c01-84a8-e17a90323903)

**Comment by ndiego** [comment]
> Remove the drop cap
> Remove the pagination from the content (it's in the template)
> Remove the reusable block table of contents (https://github.com/WordPress/wporg-mu-plugins/pull/650)
> Update the notice blocks to use "Notice", not "Callout" (for the redesign style & icons)

@harishankerr FYI. I am happy to go in and take care of these content updates once the site is launched tomorrow. Are you comfortable with me doing that?

**Comment by harishankerr** [comment]
> - Remove the drop cap
> - Remove the pagination from the content (it's in the template)
> - Remove the reusable block table of contents (https:/github.com/WordPress/wporg-mu-plugins/pull/650)

All these are done. I'll try and see if I can add the "notice" in there before the deadline as well, @ndiego.

**Comment by ndiego** [comment]
> All these are done. I'll try and see if I can add the "notice" in there before the deadline as well, @ndiego.

Amazing, this can be done post-launch as well.

**Comment by harishankerr** [comment]
> Update the notice blocks to use "Notice", not "Callout" (for the redesign style & icons)

I spoke too soon, this is also now done!

**Comment by ndiego** [comment]
Thanks @harishankerr! 

@ryelle I think this issue can be closed, but I defer to you.

**Comment by ryelle** [comment]
Looks good, thanks @harishankerr !
