### ISSUE TITLE
Background color of Global header, Local nav, and Hero section in Homepage

### ISSUE THREAD

**Issue by fcoveram** [WordPress/five-for-the-future#311]
URL where issue is: All pages, and hero section in Homepage

Browser you're using: Arc 1.59.0 (53388)

## What do you see?
The background color of Global header, local nav, and hero section is `color--charcoal-2`. The latter only impacts the homepage. Here is a screenshot tagging the three sections mentioned

![Five for the future's homepage with notes in three sections](https://github.com/user-attachments/assets/14e52fc5-d323-4557-a05e-adeb7dbaa8a9)

## What should be changed?
The color should be `color--charcoal-0`

**Comment by ryelle** [comment]
@fcoveram Did you mean `charcoal-1` (#1E1E1E, matching showcase), or `charcoal-0` (#1a1919)? The mockup has `charcoal-1` ("Foundational/WP.org Charcoal").

**Comment by fcoveram** [comment]
You're right. I meant `charcoal-1`, as in the mockups.
