### ISSUE TITLE
New Theme: Add spacing between testimonials on mobile.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#312]
On the testimonials page, the subjects should be separated more on mobile.

URL: https://wordpress.org/five-for-the-future/testimonials/ 

<img width="417" alt="Screenshot 2024-09-13 at 9 43 08 AM" src="https://github.com/user-attachments/assets/e9eae293-649e-4a6a-93f9-000d9ee94812">

**Comment by ryelle** [comment]
In the screenshot, this is using Large (60) `clamp(20px, calc(10vw - 40px), 80px)` — I've updated the page to Medium (50) `clamp(40px, calc(5vw + 10px), 60px)`, so it'll be 40px on small screens, and 60px on large. Does this work? cc @fcoveram

<img width="841" alt="Screenshot 2024-09-13 at 12 00 20 PM" src="https://github.com/user-attachments/assets/ab79a4d1-f4ae-424c-b113-264b4064d95a">

<img width="445" alt="Screenshot 2024-09-13 at 12 00 39 PM" src="https://github.com/user-attachments/assets/df6bf12b-2157-4c5e-82c2-5501e18c9506">

**Comment by fcoveram** [comment]
This looks great 🚀
