### ISSUE TITLE
New theme: Link teams in the profiles.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#314]
We show the teams in the sidebar for each pledge. As a prospective pledge, I would be interested in viewing that team. Can we link those so they bring you to the team description on make?

## Screenshot

<img width="484" alt="Screenshot 2024-09-13 at 9 51 15 AM" src="https://github.com/user-attachments/assets/4c382348-1fcb-4832-bd94-543d6a92913f">

### Replace with links.
<img width="496" alt="Screenshot 2024-09-13 at 9 52 25 AM" src="https://github.com/user-attachments/assets/54e9034b-d86c-46da-b449-6b97de13851d">

**Comment by ryelle** [comment]
What do you think these should link to?

Rather than making each a link (which would be a lot of underlined text), I'm inclined to add a "learn more" style link or button linking to `https://make.wordpress.org/`. Something like this, which would work for the companies with few teams, too:

<img width="496" alt="Screenshot 2024-09-13 at 12 08 14 PM" src="https://github.com/user-attachments/assets/3cd7f741-3903-4a3b-a447-f748fb1c0864">

But maybe with better text than "View all team opportunities" :)

**Comment by fcoveram** [comment]
Agree with @ryelle, I think a single link to Make would keep the layout clean while being appealing. What the label for this could be @thetinyl?

**Comment by thetinyl** [comment]
> What the label for this could be @thetinyl?

Gooooood question. So I can see a world where we could be very simple and clear and to-the-point with something like: See all contributor teams 

Or we can frame it a little differently like: Learn more about contributor teams

**Comment by ryelle** [comment]
I like "Learn more…", which works since make.w.org has little blurbs about each, and links to the contributor quiz.

**Comment by thetinyl** [comment]
> I like "Learn more…"

Yeah, that's my preference, too. I'm comfortable going with that. We can always adjust if someone feels differently.

**Comment by fcoveram** [comment]
I also like the "Learn more…" version. Let's go with that 🚀

**Comment by StevenDufresne** [comment]
> What do you think these should link to?

I don't think we have an interesting place to link them to yet, however, I would expect them to link to their equivalent make blog which includes information about the team in the Welcome box (which won't be collapsed for new users). So for core: https://make.wordpress.org/core.

Regarding adding a link below the teams... I think that is a logical and _neat_ solution and I'm ok with that. I still think we should linking the teams directly everywhere they are referenced. I beleive the team names are clear enough that a user's initial instinct of whether that team makes sense for them is likely correct and they should enter the contributor funnel immediately. I wouldn't want to impede users ability to get started because it would visually be unappealing. I would prefer we rethink the layout/design if that's the case.

| Header | Header |
|--------|--------|
| <img width="1268" alt="Screenshot 2024-09-19 at 9 04 14 AM" src="https://github.com/user-attachments/assets/ee9852de-4ae0-4801-9b0b-37a10d598aff"> | <img width="1276" alt="Screenshot 2024-09-19 at 9 03 59 AM" src="https://github.com/user-attachments/assets/40a60302-14d8-4881-ade6-a1519df6f6ea"> | 

I don't feel it's too distracting. Can we try it as an experiment? If no one clicks a team link within 2 weeks, we can revert?

**Comment by fcoveram** [comment]
> I beleive the team names are clear enough that a user's initial instinct of whether that team makes sense for them is likely correct and they should enter the contributor funnel immediately. I wouldn't want to impede users ability to get started because it would visually be unappealing. I would prefer we rethink the layout/design if that's the case.

Good point. Regarding a new design, I proposed one in #321 that taps into your suggestion.

> Can we try it as an experiment? If no one clicks a team link within 2 weeks, we can revert?

+1 to this. We can try it and see how it works.

**Comment by ryelle** [comment]
Does every team have a unique p2? I'm not sure. I still think landing on the Make homepage and getting more details on each team/seeing the contributor quiz would be a better experience than dropping people right onto a P2, even with the welcome box.

> Can we try it as an experiment? If no one clicks a team link within 2 weeks, we can revert?

How can we get this data to know whether this works? Would we also test out a single "learn more" button to compare?

**Comment by thetinyl** [comment]
> I'm not sure. I still think landing on the Make homepage and getting more details on each team/seeing the contributor quiz would be a better experience than dropping people right onto a P2, even with the welcome box.

Not a strong opinion, but I do agree with @ryelle. Most pledge pages won't have all/most of teams listed either, so why not lead a prospective pledge to the full list (i.e. Make homepage) that has every team's mini description.

**Comment by StevenDufresne** [comment]
> Not a strong opinion, but I do agree with @ryelle. Most pledge pages won't have all/most of teams listed either, so why not lead a prospective pledge to the full list (i.e. Make homepage) that has every team's mini description.

Okay. Let's go with a link then. 👍
