### ISSUE TITLE
New Theme: Add contributor count to "Contributor" page heading.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#315]
On the pledge page, we show all the contributors but only list the count in the sidebar. It's very missable. Can we append it to the title?

URL: https://wordpress.org/five-for-the-future/pledge/automattic/

| Before | After |
|--------|--------|
| <img width="1208" alt="Screenshot 2024-09-13 at 9 53 45 AM" src="https://github.com/user-attachments/assets/97552fbe-d4d0-475d-9473-373c42921305">  | <img width="1267" alt="Screenshot 2024-09-13 at 9 53 31 AM" src="https://github.com/user-attachments/assets/d25bdc18-ae30-4333-85f6-25f3c1221509">  |

**Comment by ryelle** [comment]
I'm not sure about this. If there are a lot of people, you can see many avatars, and I don't know if the difference between 105, 44, and 33 (top 3 contrib) is really close enough to need a reminder statistic. If there are few, you can probably count quickly that there are few, and having the count there would just be obvious 🙂 

For example, [Bluehost](https://wordpress.org/five-for-the-future/pledge/bluehost/) (which is still on the first page when sorted by contributors), or with the median of 3 pledges, [Omnisend](https://wordpress.org/five-for-the-future/pledge/omnisend/).

![Screen Shot 2024-09-13 at 12 37 56](https://github.com/user-attachments/assets/5e2b26ad-55a1-4ca9-b353-65d172f18453)

![Screen Shot 2024-09-13 at 12 38 08](https://github.com/user-attachments/assets/b3805452-0b4f-4776-a697-3cd7d3884cc8)

Related, I had suggested using these stats in the opengraph description, but @thetinyl [pointed out](https://github.com/WordPress/five-for-the-future/issues/304#issuecomment-2341840659) that it's not really as impressive for the smaller orgs. It feels like the same would apply here.

**Comment by thetinyl** [comment]
Taking into account the entire page, my read on the "Contributors" section is more about showing **who** the contributors are, less about how many. 

I don't think adding the number there adds any value. Or at least, not more so than keeping it with all the other stats in the sidebar.

**Comment by StevenDufresne** [comment]
Good points.
