### ISSUE TITLE
New Theme: Use appropriately size gravatar images.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#317]
Regardless of where the avatar image is loaded, it will pull in the gravatar image as `s=560`. That is far too large and unnecessary (and hurts performance). 

**Pages Affected:**
- Pledge List: https://wordpress.org/five-for-the-future/pledges/
- Single Pledge: https://wordpress.org/five-for-the-future/pledge/automattic/

**Comment by pkevan** [comment]
Looks like the avatars are pulled at 280px, with the 560px ones being used at 2x for retina.

Although, it does make sense to reduce these in size.
