### ISSUE TITLE
Landmark Issues Complicate Screen Reader Navigation

### ISSUE THREAD

**Issue by bbertucc** [WordPress/five-for-the-future#325]
## Problem
Screen readers can't navigate to a section based on its HTML element or ARIA Landmark because some Five to the Future content is not contained in landmarks and some landmarks are not unique.

### Landmarks that Aren't Unique
All Five to the Future pages include two `<header>` elements, one nested in the other. There are also duplicate `<footer>` elements, one nested in the other. That prevents screen reader users from distinguishing the different elements because they are both read out as the same thing.

### Uncontained Content
Various elements are not contained in any Landmark. This means they are skipped if a screen reader user is navigating by landmarks. I compiled a list of uncontained content in this CSV: 
[uncontained-elements.csv](https://github.com/user-attachments/files/17134769/uncontained-elements.csv)

### Example
On https://wordpress.org/five-for-the-future/testimonials/, you'll notice both unique landmarks and uncontained content.

**Comment by ryelle** [comment]
Yesterday I deployed fixes for the header & footer issues, and I updated the `article` wrappers to be `main`, matching the other sites. I think this is fixed now, can you take a look?

**Comment by bbertucc** [comment]
Yep! Looks like this is fixed. Awesome work @ryelle! Closing this issue.
