### ISSUE TITLE
Pledges: Create system for generating and validating temporary confirmation links

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/five-for-the-future#34]
There are several parts of this system that are going to rely on the user confirming something or accessing something by clicking a unique link that they receive in an email.

* Confirm the email address associated with a pledge #10 
* Access and manage an existing pledge #5 
* Confirm a contributor connection to a pledge #12 
* Remind pledge owners to update their info #27 

Ideally, I think, these links would be true one-time use. But if building that system is too complex, utilizing WP's nonce system might be sufficient.

**Comment by iandunn** [comment]
I considered just using WP "nonces" for this, but ultimately didn't feel comfortable enough with it from a security perspective, and am working on a true NONCE system.

The WIP is in https://github.com/WordPress/five-for-the-future/compare/email-auth if anyone has any high-level concerns about the overall direction.

**Comment by coreymckrill** [comment]
What are your concerns with the not-nonces in WP?

**Comment by iandunn** [comment]
I cleaned up the branch comments to highlight that:

https://github.com/WordPress/five-for-the-future/commit/f5505a6e89b512c6f91f88f1dedd205090b9a908#diff-386d765255eaba2bb2d14729a85ca929R3-R22

https://github.com/WordPress/five-for-the-future/commit/f5505a6e89b512c6f91f88f1dedd205090b9a908#diff-386d765255eaba2bb2d14729a85ca929R97-R102
