### ISSUE TITLE
Allow admins to edit pledge page content

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#41]
`[five_for_the_future_companies]` has a lot of content hardcoded, but it seems like that could be in `post_content` instead, so that admins can easily edit it without needing a dev to commit/deploy code.

If that's right, then the only thing that needs to be rendered by the shortcode is the table of data.

**Comment by ryelle** [comment]
The shortcode isn't going to be used, we're using the pledge's CPT archive view. See #14 

And there isn't any content on the pledge list page - see the design in #32.

**Comment by iandunn** [comment]
WFM. I'll leave this open to ensure we delete the unused shortcode/content.

**Comment by iandunn** [comment]
Deleted in 6cd710b71da082a9fe4df6ff64ab5a58dfd47aab
