### ISSUE TITLE
Remove 'Number of Employees Being Contributed' field?

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/five-for-the-future#48]
This field seems superfluous, because the pledge also has contributor entities attached to it. We can simply count the number of confirmed contributors rather than relying on an arbitrary number input. In fact, I would guess that the number input would frequently be different than the number of confirmed contributors, which would potentially create confusion.

Update:
In addition to removing the field, we should "cache" the count of confirmed contributors for a pledge in a postmeta value so it can be used more easily in the archive query and the single pledge view.

**Comment by ryelle** [comment]
We probably don't need the field in the form, but it would be good to track number of approved contributors in post meta. We need to be able to sort the archive list by "Total Contributors", and meta will be the easiest way.

**Comment by andreamiddleton** [comment]
I agree that we probably don't need this field in the form.

**Comment by coreymckrill** [comment]
Decision: We're going to remove the input field, but have a generated post meta value with the count of confirmed contributors.
