### ISSUE TITLE
Manage an existing pledge: generate one time use edit link

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#5]
A pledge owner can click a link on a pledge, and is taken to a new page? Modal? to enter their email address. On submit, check if the email matches the pledge owner. If it does, we'll send them an email with a one time use link. If not, some error message?

The one time edit link will need to have info about which pledge should be edited, see CampTix access/edit links.

cc @melchoyce – for input on the form design & modal q. Single pledge will also need a "edit this pledge" link.

**Comment by ryelle** [comment]
@melchoyce to give you a more coherent idea of the design need here… If you're a pledge owner and you want to edit your pledge, we need to verify your email first. So we need:

- A link/button somewhere to "edit" a pledge (on the pledge screen? somewhere else? this would be visible to everyone, it's not behind a logged in check)
- Once clicked, we need to get the user's email, so that we can match it against existing pledges and email them a special link to edit their pledge.

The link that's emailed will send them to a form very similar to the create form, but with the pledge info already filled out, so they can edit it & save to update.

**Comment by melchoyce** [comment]
Why no logged in check?

**Comment by ryelle** [comment]
Because we don't want pledges tied to a specific wp.org profile, to prevent "company accounts". It could be visible to all accounts listed as "contributor" to that pledge though?

**Comment by melchoyce** [comment]
Hmm, but if the person who created the pledge doesn't have a .org account (say, an administrative assistant or manager), they wouldn't have access. I'll look at the original flow you described.

**Comment by melchoyce** [comment]
Does this work?

![image](https://user-images.githubusercontent.com/2846578/66607039-5ae86900-eb81-11e9-8c6b-0a22b0ad640d.png)

**Comment by ryelle** [comment]
Perfect, thanks! Minor note – we've casually been using "pledge owner", not "pledge admin", we'll just want to make sure we stick with one term anywhere visible (IMO admin is better).
