### ISSUE TITLE
Duplicate contributor posts are created

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#55]
When a pledge is submitted, contributor posts are created for the listed contributors, but there isn't a check if they've already been submitted by other organizations, so duplicate posts are created.

**Comment by ryelle** [comment]
Is this a problem? We talked about this [on the doc](https://docs.google.com/document/d/1p3k-jqE4mi-TyIc-Sz9L_g25_VitjsPj2TcWuuqXjKw/edit?disco=AAAADjofOeA) – since each contributor can only have one parent pledge, the post is more "per user per pledge", not per wp.org user.

> The idea is that each contributor that is linked to a pledge is a distinct entity with its own meta data (e.g. whether or not they've confirmed, and maybe some things pulled from Profiles like how many hours they are sponsored for, which teams, etc.) The most efficient way to manage these entities and their data within our existing data architecture seems to be a post type. This wouldn't be used for individual contributors' pledges, only contributors that are linked to an organization's pledge.

**Comment by iandunn** [comment]
🤔 , you're right. 

In hindsight that seems counter-intuitive, and it's also re-creating what is essentially a person/user account. I wonder if multiple `wp_usermeta.5ftf_pledge` items would fit better, which each of them being `array( 'pledge_id', => n, 'status' => 'pending', etc )`.

Probably not worth doing anything at this point, though.

**Comment by iandunn** [comment]
🤔 , although, we wouldn't be able to query for all of the contributors to a pledge directly if w/ the `usermeta` above. We could store `user_id`s in `post_meta` for the `pledge` post type, but that would be kind of redundant. Although maybe we already have that redundancy in the existing approach as well, so 🤷‍♂
