### ISSUE TITLE
Add My Pledges to navigation menu?

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#58]
There should probably be a way for contributors to access their pledges on the site itself, not just from Profiles, since it's unintuitive to have the link to a page be on a completely different site.

We could programmatically add it to the nav menu when users are logged in, or maybe something else.

**Comment by coreymckrill** [comment]
I was thinking that it should be shown in the nav menu when a user is logged in.

**Comment by iandunn** [comment]
Fixed in fe437cc880bbd60156dfa9b416af93f8139c3188
