### ISSUE TITLE
Pledge Form: Allow HTML in organization description

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/five-for-the-future#63]
Some orgs have HTML, especially links, in their description. We should allow this.

**Comment by iandunn** [comment]
I think we should pass the input through `wp_targeted_link_rel()`, and probably use `wp_kses_data()` (comments) so it's just very basic HTML.

**Comment by iandunn** [comment]
Er, `wp_targeted_link_rel()` only affects links that have a `target`, but I don't think these should open in a new window.

I thought there was a Core function that would do it to all links, but I'm not seeing it right now, so maybe we'll need to write a custom one or something.

**Comment by coreymckrill** [comment]
Are you thinking of `wp_rel_nofollow`?

**Comment by iandunn** [comment]
Ah, yes! Thanks :)

**Comment by ryelle** [comment]
If we allow HTML and maybe multiple paragraphs, we should probably trim the description for the list view with `wp_trim_words`.

**Comment by iandunn** [comment]
e61ce46 allowed HTML, but I forgot to add `wp_trim_words`

**Comment by iandunn** [comment]
Trimmed in 2dcdcd939c35f4990e4d1951aa0fd8e2352ee8bb
