### ISSUE TITLE
Pledges: Contributor image alignment is off

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#66]
We need space between each image (about 4px) on the list page:

<img width="624" alt="Screen Shot 2019-10-30 at 2 09 39 PM" src="https://user-images.githubusercontent.com/541093/67890572-f6d11900-fb1e-11e9-85ee-4c1d3f3681bc.png">

On single pages, avatars should be left-aligned.

<img width="975" alt="Screen Shot 2019-10-30 at 2 10 35 PM" src="https://user-images.githubusercontent.com/541093/67890629-0fd9ca00-fb1f-11e9-865b-405ca6804bbe.png">

**Comment by iandunn** [comment]
It looks like the padding between avatars is done now. Is there anything else left to do?

**Comment by ryelle** [comment]
No, it's still wrong when one or two people end up on one line – I have a fix locally, there's just still an edge case with responsive, I can push that today.

<img width="1030" alt="Screen Shot 2019-11-01 at 7 51 05 AM" src="https://user-images.githubusercontent.com/541093/68026029-69a3d680-fc7c-11e9-9574-89d896dfeece.png">
