### ISSUE TITLE
Show all contributors for a given team

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#69]
This will help team reps find people to work on projects

**Comment by iandunn** [comment]
It should probably include non-sponsored contributors too, though, so maybe it should live on the make p2s instead of here?

**Comment by iandunn** [comment]
Here's a rough wireframe of showing it on Make blogs, and the kind of info we might want to include:

<img width="1016" alt="Screen Shot 2019-11-04 at 12 18 21 PM" src="https://user-images.githubusercontent.com/484068/68146282-463b8e80-fefd-11e9-902b-9a49de5d1099.png">

I'm thinking we'd automatically create a `make.w.org/{team}/contributors` page for each team, and include the above info for all the people (sponsored and not) who have marked that team on their profile. 

If they're sponsored, the "Sponsored" links would go to their company's 5ftF pledge page. If not, we'd use the team "volunteer" to highlight that their contribution is even more significant than sponsored folks'.

We can't show only the # of hours that the contributor commits to the individual team, because we don't track that info on Profiles. We only track how much they commit across all teams.

In terms of functionality, does that sound good to people?
@andreamiddleton, @melchoyce , @ryelle , @coreymckrill

**Comment by andreamiddleton** [comment]
Maybe just one tweak to the vocabulary: 

`make.w.org/{team}/pledges` rather than `make.w.org/{team}/contributors`

> If they're sponsored, the "Sponsored" links would go to their company's 5ftF pledge page. If not, we'd use the team "volunteer" 

This seems like a good approach.

**Comment by melchoyce** [comment]
Would something like this work?

![image](https://user-images.githubusercontent.com/2846578/68966006-1c128800-07ab-11ea-9371-16b5789171ec.png)

**Comment by ryelle** [comment]
Looks great, thanks!

I've marked this low priority for now since it's an enhancement to the make sites, not a requirement for Five for the Future directly.

**Comment by iandunn** [comment]
I'm making progress on this. Once it's done, how should we let people know that the new page exists? The two things that jump to mind are:

1. Publishing a post on `make/Updates`
1. Automatically add a widget to the bottom of each team's sidebar. It could show avatars like https://wordpress.org/five-for-the-future/pledges/, or just be a text link to the page.

I like the idea of doing both, because if we only write the `make/Updates` post, then most people won't be aware, because they don't read that site, and even those who do will eventually forget how to find the info and have to dig through old posts to find the link. 

If we only do the sidebar widget, then most people will never notice that it's there.

If we do both, though, then I think the combination will create enough institutional knowledge to make it something that most active contributors are aware of.

Any thoughts?

**Comment by iandunn** [comment]
🤔 I'm second-guessing the idea to highlight volunteer contributors' extra sacrifice; I'm worrying that  people might interpret that the opposite of how it's intended, like "they're _only_ volunteering, so it's not a _real_ contribution" ?

Part of that worry might be caused by the current copy explicitly saying "contribute" for sponsored folks, but only implying it for non-sponsored folks. Tweaking it to the following might help avoid that:

* Volunteers to contribute N hours per week
* Sponsored to contribute N hours per week

I still kinda worry that people might assume the worst, though 🤔 

What do y'all think?

**Comment by coreymckrill** [comment]
I think using `contribute` for both instances helps.

**Comment by iandunn** [comment]
One thing that's become apparent while building this is that there are a _lot_ of contributors on each team (mostly volunteer).

For example:

* Community: `682`
* Design: `444`
* Core: `456`
* Training: `292`
* Meta: `191`

That's probably affected a lot by the inaccuracy of the self-reported data (see #83), but regardless, it'll make it pretty hard for team members to use the page for its intended purpose. 

I wonder if we should add some filtering based on whether or not someone is sponsored, and/or sorting by hours contributed?

**Comment by iandunn** [comment]
Maybe another helpful filter would be an option to only show people who have the corresponding `{Team} Contributor` badge on their profile?

**Comment by melchoyce** [comment]
I think that would definitely help cut down on the inaccuracies — and encourage contributors to make sure they get properly credited!

**Comment by iandunn** [comment]
🤔 maybe that `has contributor badge` filter should be set in the default view, so that the user doesn't have to take any action to get the most useful data? But they could also switch over to the `view all` view to see everyone. 

Maybe a `doesn't have contributor badge` filter would even be helpful for team reps to identify people who _have_ contributed, but haven't been officially credited? That might be outside the scope of this page, or maybe just worth noting as a future iteration, but might be pretty easy to do 🤷‍♂

**Comment by iandunn** [comment]
The first parts of this are done in `dotorg 15614` and https://meta.trac.wordpress.org/changeset/9320/.

e.g.,

* https://make.wordpress.org/community/pledges/
* https://make.wordpress.org/design/pledges/
* https://make.wordpress.org/meta/pledges/
* https://make.wordpress.org/core/pledges/

It automatically exists for all of the Make sites that have a corresponding `make_site` CPT post.

I opened new issues for iterations:

* filters: https://github.com/WordPress/five-for-the-future/issues/129
* publicizing: https://github.com/WordPress/five-for-the-future/issues/130
* lazy-load gravatars: https://github.com/WordPress/five-for-the-future/issues/131
