### ISSUE TITLE
Report a Pledge form

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#8]
If a pledge contains inappropriate content, a site visitor should be able to report it. We'll use a contact form that will send to [email TBD]. Let's make sure to have spam filtering on this.

**Comment by coreymckrill** [comment]
Can we just use a contact form block from Jetpack on a page? Or are there reasons to build a custom form instead? Maybe we don't want these reports being stored as Feedback posts in the database?

**Comment by iandunn** [comment]
I can't think of any reasons they shouldn't be in the database, so a contact form block seems simplest.

**Comment by coreymckrill** [comment]
This is done. The title we are currently using is actually "Report a problem".
