### ISSUE TITLE
Link "Sponsored" info on profile page to employer

### ISSUE THREAD

**Issue by jdevalk** [WordPress/five-for-the-future#82]
If a user is sponsored for their contribution, it shows on their profile page with a "Sponsored" page, like so: 

<img width="914" alt="Screen Shot 2019-11-04 at 18 24 18" src="https://user-images.githubusercontent.com/487629/68142784-60429480-ff30-11e9-891d-bfb71914e014.png">

They are sponsored by a company that lists them on that company's pledge page, but there's no link back from the profile page to the pledge page. My suggestion would be to change this to this:

<img width="914" alt="Screen Shot 2019-11-04 at 18 24 06" src="https://user-images.githubusercontent.com/487629/68142791-646eb200-ff30-11e9-81ca-8f6c15ce1512.png">

This would also allow future iterations for issues like #72.

**Comment by iandunn** [comment]
This makes sense to me. I think the phrasing might flow a bit smoother like this:

> [Yoast](#) sponsors Joost de Valk to contribute 4 hours per week to the [Core](#), [Hosting](#), [Marketing](#), and [Meta](#) teams.

Contributors who volunteer their time could maybe have something like this:

> Jane Smith contributes 4 hours per week to the [Core](#), [Hosting](#), [Marketing](#), and [Meta](#) teams.

@andreamiddleton, how does that sound to you?

**Comment by dd32** [comment]
Also requested in https://meta.trac.wordpress.org/ticket/5367

**Comment by andreamiddleton** [comment]
This sounds like a perfectly appropriate change to me.

**Comment by iandunn** [comment]
Done in `r18678-dotorg`
