### ISSUE TITLE
Clarify contributor team names

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#83]
Many company pledges seem to be confusing work on building/supporting their individual plugins/themes to be 5ftF contributions. In a broad sense, those are definitely contributions to the WP ecosystem, but I don't think they're Five for the Future contributions.

To help clarify things, I think it'd be good to do the following, both on `profile/edit/group/5/`, and on various `w.org/5` pages:

- [x] Rename `Themes` to `Theme Review Team` (both `xprofile_fields` and `xprofile_data`)
- [x] Remove `Plugins` and `Security`, since they're closed groups
- [x] Prevent `PRT` and `Security` from accidentally being added to the Teams field in the future, and document why they're not there - `dotorg 15598`
- [x] Remove non-`PRT`/`Security` members who previously assigned themselves to that group incorrectly
- [x] Change `Teams` label on profile edit screen to `Official Contribution Teams` - `[dotorg 15609]`
- [x] Add `Team` postfix to each entry, to make it clear that it's a specific team, not just the broad idea of `support`, `community`, etc. e.g., `Support Team` instead of just `Support`. - `[dotorg 15609]`

We don't need to rename any of the underlying data in Profiles, we can just modify the strings that are displayed on the fly.

Props @coffee2code for [the idea](https://meta.trac.wordpress.org/ticket/4826#comment:2).

**Comment by earnjam** [comment]
Should the contribution teams listed on individual user profiles _only_ be tied to the BuddyPress groups that drive the badges instead of self-selected? Or perhaps since you might be sponsored to contribute to certain teams, but have badges from more than that, just filter the list you can select down to those you are a member of? 

When those teams entirely are self-selected, it also looks like it bubbles up to the company pledge page, so its a bit misleading and unclear where those company page badges are coming from. 

Two issues I can think of with this is that since many of those BP groups are manually managed, they tend to stagnate and aren't updated regularly with current contributors. Also, if someone is making a new pledge, but hasn't begun contributing yet, it would take some time before their pledged hour/team contributions showed up in the Five for the Future site.

**Comment by pattonwebz** [comment]
@iandunn will we need to do the same for themes and add these 2 items to the list?

- [ ] Manually add TRT members to the group so they still get credit for their contributions
- [ ] Remove non-TRT members who previously assigned themselves to that group incorrectly

**Comment by pattonwebz** [comment]
@earnjam if you know who I can talk to about getting management access to the buddypress group for themes review team badges I can totally get on top of making that list current and keeping it updated on a more regular basis :)

**Comment by iandunn** [comment]
> Should the contribution teams listed on individual user profiles only be tied to the BuddyPress groups that drive the badges instead of self-selected?

That's an interesting idea. It'd definitely help prevent this kind of confusion, but I also worry that it'd create a barrier for new contributors, for the reasons you mentioned. One of the critical use cases is when someone essentially says  "I want to start contributing to this team X hours a week", and then the team rep reaches out to them to get them involved in specific projects (see #36 , #69).

**Comment by iandunn** [comment]
> will we need to do the same for themes and add these 2 items to the list?

🤔 That's a good question. It'd be a bit more complicated w/ TRT than PRT, since it's an open group and people could be indicating that they _intend_ to start contributing to it. Rather than removing people, maybe it'd be better to send out an email with some clarifying details, and ask them to update their profile if they chose incorrectly before?

**Comment by pattonwebz** [comment]
> > will we need to do the same for themes and add these 2 items to the list?
> 
>  That's a good question. It'd be a bit more complicated w/ TRT than PRT, since it's an open group and people could be indicating that they _intend_ to start contributing to it. Rather than removing people, maybe it'd be better to send out an email with some clarifying details, and ask them to update their profile if they chose incorrectly before?

Yeah that was partially my concerns there. So no on auto-add/remove for TRT but I will make sure to reach out and ask them where appropriate. Once #36 and #69 are worked on that will be a lot easier to do.

**Comment by andreamiddleton** [comment]
> Rename Themes to Theme Review Team.
> Remove Plugins since the PRT is still a closed group
> Manually add PRT members to the group so they still get credit for their contributions
> Remove non-PRT members who previously assigned themselves to that group incorrectly
> Add Team postfix to each entry, to make it clear that it's a specific team, not just the broad idea of support, community, etc. e.g., Support Team instead of just Support.

I think these are all strong ideas! I'd say to go ahead with them. :) 

I also think we need a FAQ explaining the intent of the pledge program, and defining what kind of WordPress work we're trying to acknowledge with it. That page could cover the last two ideas in your list, Ian.

**Comment by aaronjorbin** [comment]
I think there may need to be some clarification with the community team. For instance, person who is organizing a wordcamp would, in my opinion, be donated to the community team but they aren't necessarily a part of the team who meats in #community-events (or similar channel)

**Comment by andreamiddleton** [comment]
I might be a little biased, but from my perspective, WordCamp & meetup organizers are definitely contributing; just like how local translations teams are contributing even if they're not working on the "global" polyglots team.

**Comment by aaronjorbin** [comment]
Oh, I wasn't trying to imply they weren't. I was just wondering if we wanted to clarify that contribution so it's clearer "My time is being donated to help build my community" and "My time is being donated to help others build communities"

**Comment by andreamiddleton** [comment]
Aaron, that is a beautifully expressed distinction! I think that if this program catches on, we might eventually want to add a Role option (ie: I contribute 5 hours per week as a `Community Team Deputy`, 1 hour per week as a `Meetup Organizer`, and 2 per week as a `Support Forum Volunteer`) -- though, until more teams have slightly more formalized roles, I don't think it's practical.

**Comment by iandunn** [comment]
I moved the last two items on the checklist to https://github.com/WordPress/five-for-the-future/issues/119, since everything else is agreed on.

**Comment by iandunn** [comment]
For the Plugin Review and Security teams, I think we could probably automatically add those badges under sponsorship, since they're both closed groups. If it were just PRT then doing it manually would be fine, but Security is much larger, so it'd be helpful to automate it.

**Comment by andreamiddleton** [comment]
I think PRT is trying to expand, but even with a few new people they're less than 6 folx, I think. For the Security team, I don't know the best way to automate that but I agree automation might be best. Though, since the team's roster doesn't change often, maybe just work from the current list and update quarterly?

**Comment by ryelle** [comment]
@iandunn What's left before we can close this issue? I see "Automatically add PRT and Security members to the group so they still get credit for their contributions" is still unchecked, what needs to happen to get that done?

**Comment by iandunn** [comment]
I created https://github.com/WordPress/five-for-the-future/issues/134 for the remaining item (`Automatically add PRT and Security members to the group so they still get credit for their contributions`).
