### ISSUE TITLE
Harden auth tokens by including IP in place of user ID

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#91]
_This isn't a high priority, just an idea worth making noting, in case we ever determine that the current implementation isn't secure enough._

----

`wp_create_nonce()` automatically includes the current user ID when generating the hash, but if the user is logged out that's just set to `0`, so it's the same for each pledge admin.

We could harden that by using the `nonce_user_logged_out` filter to set the ID to their IP address, since that should be unique-ish, and shouldn't change between sessions.

IPs can be spoofed, so it's not secure in-and-of itself by any means, but would be an easy way to add an additional factor.

**Comment by pkevan** [comment]
Close due to age and not a known problem.
