### ISSUE TITLE
Require contributors to fill out hours & teams before being displayed?

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#93]
Should we display contributors on pledges if they haven't filled out their # of hours per week that they contribute, and the teams that they contribute to?

It seems like that's an essential step in the process, because if it's skipped then teams can't reach out to them for help with projects, etc, because they won't show up in resources like #69.

If we do shift to not displaying them until that's done, then we could email everyone who would be affected so that they can easily fill it out and be displayed again.

Props @coreymckrill for the idea.

cc @andreamiddleton, @ryelle

**Comment by ryelle** [comment]
So we have the "Please update your profile with the number of hours per week that you contribute, and the teams that you contribute to." notification now, which directs folks over to the profiles site to update this. Right now it's very easy to ignore and just click "Join Organization".

![Screen Shot 2019-11-08 at 4 17 11 PM](https://user-images.githubusercontent.com/541093/68511690-7e680780-0244-11ea-97ad-ddf496f702e0.png)

If we're going to make the hours/teams info a blocker to being displayed, I think it needs a better flow to enter that information.

**Comment by iandunn** [comment]
Those are really good ideas!

**Comment by andreamiddleton** [comment]
I like the idea of making the "things to fill out" fields more readily available on the My Pledges page.  I think disabling the button might work well, to force the behavior we're looking for. Just a note that this will probably be a one-time-per-user issue. :)
