### ISSUE TITLE
Pledge List: Add sorting by total contributor count

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#94]
[The Pledges page](https://wordpress.org/five-for-the-future/pledges/) is sorted randomly by default, but has an option to sort by total hours as well.

What's the reason for having that? Are there any reasons to keep or remove it?

props @coreymckrill for the idea of starting this conversation.

cc @andreamiddleton, @ryelle

**Comment by iandunn** [comment]
I think the idea behind it was the same as w.org Profile badges, where we recognize that human nature is to compare yourself to others and seek status, but showing gratitude and appreciation for the hard work that people do is also critical for sustaining a volunteer community. So, we try to minimize the gamification, and make sure that when people inevitably do things in order to get badges, that they're doing things that benefit the project.

In a similar way, I do think it's helpful to display the # of hours a company contributes, but having an explicit ability to sort by them encourages comparison. That comparison doesn't help the project in any way, and it creates an unhealthy dynamic. It could also create a situation where some companies unconsciously exaggerate their hours in order to virtue-signal.

So, I think we should keep displaying the numbers, but remove the ability to sort by them.

**Comment by WPprodigy** [comment]
Really good points. Going in I was hesitant, after reading your last comment I'm all for it.

I know this isn't a reason to keep/remove per-se, but removing this also removes a rather painful query :)

**Comment by ryelle** [comment]
I agree this could be a negative metric used to game the page 🙁 

Would we want to remove sorting altogether then? Initially in the mockup, the sort options were default (now random), alphabetical, total contributors, and hours per week. It looks like https://github.com/WordPress/five-for-the-future/commit/33d3bc19339507d04f418bdd05ee31051189ca6b#diff-a4bb4c3147894ad49babad621e7827df removed "total contributors" in favor of "total hours" (we should have had both). If we really don't want to sort by total contributors _or_ total hours, that only leaves alphabetical, and I'm not sure that's useful when someone could just search for whatever company they're looking for.

Or we could bring back sorting by Total Contributors (because at least that needs real human users to confirm the pledge, maybe it's less likely to be artificially inflated?).

**Comment by WPprodigy** [comment]
I was thinking that "alphabetical" would probably be the best default sorting option for search engines / bots: See https://github.com/WordPress/five-for-the-future/issues/70#issuecomment-551329510 (This is assuming it's even possible to set a separate default, but...maybe?)

Probably shouldn't factor this decision too much, but perhaps something to keep in mind.

**Comment by ryelle** [comment]
Yeah, I think that's a different topic - by "remove sorting" I meant remove the user-facing "Sort pledges by…" dropdown.

**Comment by iandunn** [comment]
> It looks like 33d3bc1#diff-a4bb4c3147894ad49babad621e7827df removed "total contributors" in favor of "total hours" (we should have had both).

@coreymckrill , @andreamiddleton, and I discussed that during the rush to get it launched at WCUS, and agreed that it was best to remove it. The change from "default" to random was also intentional.

Speaking for myself, I don't think # of contributors is a useful metric. 5 people that are donated 20 hours per week are in a much better position to help the project with the kinds of institutional, bureaucratic (in the best sense of the word), grunt work that is difficult or impossible to do in only 1 hour a week, even if there are 100 people trying to do it.

One of the big goals of 5ftF IMO is to get more people who are able to be the backbone of a project, to do the day-to-day, year-to-year grinding that is exponentially harder to do on a volunteer basis, but is essential to sustaining a large, complex organization.

So, if we're going to compare companies, I think it'd be much more effective to do it based on # of hours rather than # of contributors. Of course, they're both problematic and have unintended side-effects, so I don't think we should do either. Either way, though, I feel pretty strongly that we should not bring back the ability to sort by # of contributors.

>  If we really don't want to sort by total contributors or total hours, that only leaves alphabetical, and I'm not sure that's useful when someone could just search for whatever company they're looking for.

Yeah, that's a really good point, I'd be in favor of just removing the sort entirely, and having the order always be randomized.

**Comment by ryelle** [comment]
> @coreymckrill , @andreamiddleton, and I discussed that during the rush to get it launched at WCUS, and agreed that it was best to remove it. The change from "default" to random was also intentional.

Yes, I remember seeing the random sort conversation, but didn't see anything about removing "Total Contribs" – in the future this would be great to add as a PR, rather than a direct commit, even if you immediately merge it, so there can be some record of discussion.

> I'd be in favor of just removing the sort entirely, and having the order always be randomized.

👍

**Comment by andreamiddleton** [comment]
The original reason I thought sorting would be a useful tool, was to make it easier for a new company to look at what other companies have pledged, and compare their own efforts to those companies they consider "comparable" to themselves, whether by level of commitment or by size. We ended up not collecting any info from companies about their size, so it seems like the ability to sort by other details, like number of hours pledged, or number of employees who contribute, might be a good way to facilitate that "calibration" process for new pledging companies.

**Comment by ryelle** [comment]
@andreamiddleton What should be the outcome of this issue? We keep the ability to sort by total hours, and bring back sorting by number of contributors?

**Comment by andreamiddleton** [comment]
I think definitely keep sorting by hours, and yeah, let's bring back sorting by number of contributors and see what happens.
