### ISSUE TITLE
Outdated copy on For Organizations page

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#97]
> The WordPress Five for the Future initiative can be more cost effective than many traditional professional development programs, as it leverages resources produced for the WordPress community, such as the learn.wordpress.org training portal and community organizer training materials.

@andreamiddleton, the reference to learn.w.org seems wrong, since the only visible content on that site is from 2013. Was that meant as a placeholder for something newer?

Also, should we link to the community organizer training materials?

Taking a step back, though, what's the reason for this text to be on the page? It seems like it's mostly just copied from the home page, and once someone gets to the form they're probably already intending to fill it out, so they don't need further convincing.

**Comment by andreamiddleton** [comment]
Thanks, I've updated the page to remove learn.wordpress.org for now.

**Comment by andreamiddleton** [comment]
I removed the reference to learn.wordpress.org. 

>what's the reason for this text to be on the page? It seems like it's mostly just copied from the home page, and once someone gets to the form they're probably already intending to fill it out, so they don't need further convincing.

My thought there is that we will likely eventually promote the program with a direct link to this page, and I want to make sure that people know what the pledge means for them.

**Comment by ryelle** [comment]
Can this issue be closed? I'm not sure there's any action to take here now.

**Comment by andreamiddleton** [comment]
Yes, we can close this. :) Thanks!
